### ISSUE TITLE
Missing CC and BCC

### ISSUE THREAD

**Issue by TrueShutDown** [SSilence/php-imap-client#113]
Message which return **getMessage()** function not contains **CC** and **BCC** information. This information are avalible in header message.
http://php.net/manual/en/function.imap-headerinfo.php
I think all data should be available form native imap_headerinfo function.

**Comment by xXXIMMATTHEWXXx** [comment]
I wil be sure to get this added!

**Comment by xXXIMMATTHEWXXx** [comment]
I have added this compatibility with my latest commits. Check the getHeaderInfo function

**Comment by xXXIMMATTHEWXXx** [comment]
This has officially been added to our imap structure.

**Comment by TrueShutDown** [comment]
Incoming (sended) message still have't BCC and CC.
