### ISSUE TITLE
Need a flagged and seen property.

### ISSUE THREAD

**Issue by abdullahseba** [SSilence/php-imap-client#114]
### Feature request or bug
This is a promising project but a few more methods would be very welcome.
I was using Afterlogic webmail which has a nice lot of functions including flagged  and IsSeen.
https://afterlogic.com/docs/webmail-lite/integration-and-development/web-api/receiving-mail
https://afterlogic.com/docs/webmail-lite/integration-and-development/web-api

**Comment by xXXIMMATTHEWXXx** [comment]
I will look futher into this and see it it can be added!

**Comment by xXXIMMATTHEWXXx** [comment]
I have added this compatibility with my latest commits. Check the getHeaderInfo function

**Comment by abdullahseba** [comment]
Thanks but it seems to be causing an error:
`Parse error: syntax error, unexpected 'funtion' (T_STRING), expecting variable (T_VARIABLE) in C:\xampp\htdocs\php-imap-client-master\ImapClient\IncomingMessage.php on line 323`

**Comment by xXXIMMATTHEWXXx** [comment]
I have ficrd this issue

**Comment by abdullahseba** [comment]
Assuming my code is correct I'm still getting `Uncaught  error 'Imap' not found`
```
<?php
require_once "ImapClient/ImapClientException.php";
require_once "ImapClient/ImapConnect.php";
require_once "ImapClient/ImapClient.php";
require_once "ImapClient/IncomingMessage.php";
require_once "ImapClient/TypeAttachments.php";
require_once "ImapClient/TypeBody.php";


$mailbox = 'mail.e17pumphouse.org.uk';
$username = 'enquiries@e17pumphouse.org.uk';
$password = 'password';
$encryption =  null; // or ImapClient::ENCRYPT_SSL or ImapClient::ENCRYPT_TLS or null

try{

$imap = new Imap($mailbox, $username, $password, $encryption);
# ... and further code ...

}catch (ImapClientException $error){
    echo $error->getInfo();
};     
```

**Comment by xXXIMMATTHEWXXx** [comment]
ImapClient is the correct class name. Will update docs

**Comment by abdullahseba** [comment]
Finally got through 🥇 . But 
```
$folders = $imap->getFolders();
var_dump($folders);
# and
foreach($folders as $folder) {
    echo $folder;
}
```
returns a "Array to string conversion"  error.

**Comment by abdullahseba** [comment]
`implode()` works...

**Comment by xXXIMMATTHEWXXx** [comment]
Hmm... We may need to call implode internally

**Comment by abdullahseba** [comment]
Yeah.. A json output would also be useful.

**Comment by xXXIMMATTHEWXXx** [comment]
AH! I forgot to convert the array to json! Will do!

**Comment by sergey144010** [comment]
`
    /**
     * Returns all available folders
     *
     * @param string $separator. Default is '.'
     * @param int $type. Has three meanings 0,1,2.
     * If 0 return nested array, if 1 return an array of strings, if 2 return raw imap_list()
     * @return array with folder names
     */
    public function getFolders($separator = null, $type = 0)
`

**Comment by abdullahseba** [comment]
Why don't the docs mention this?

**Comment by xXXIMMATTHEWXXx** [comment]
That will be added. Thank you for pointing that out. We are currently ironing out our docs,

**Comment by xXXIMMATTHEWXXx** [comment]
Fixing with my doc updates.
