### ISSUE TITLE
Should be able to access filename for an attachment without looping over dparameters

### ISSUE THREAD

**Issue by hhdivil** [SSilence/php-imap-client#117]
This is what I'm doing to get the filename for an attachment - would be better if each attachment was a custom object and could just call a method on that object to get the filename - e.g. getFilename()

`$name = '';
foreach ($att->structure->dparameters as $dparam) {
  if ($dparam->attribute == 'filename') {
    $name = $dparam->value;
    break;
  }
}`

**Comment by xXXIMMATTHEWXXx** [comment]
So you mean an object like how our messages are. IncomingMessage and OutgoingMessage?

**Comment by hhdivil** [comment]
Yeah that would be sweet! I can probably lend a hand if you need let me
know :)

**Comment by xXXIMMATTHEWXXx** [comment]
We always take help! I will add this to the list and make sure it gets done! Feel free to open a pull request!

**Comment by xXXIMMATTHEWXXx** [comment]
Fixed with merged pr
