### ISSUE TITLE
Send message still haven't BCC and CC.

### ISSUE THREAD

**Issue by TrueShutDown** [SSilence/php-imap-client#122]
Hi 
Incoming (send) message still haven't BCC and CC.

**Comment by xXXIMMATTHEWXXx** [comment]
By send you mean messages that are received by our library? If so yes, cc and bcc is added.
```php
$imap->incomingMessage->header->details->cc
# or
$imap->incomingMessage->header->details->bcc
# cc and bcc it is array of objects with properties [personal, adl, mailbox, host]
 ```

**Comment by TrueShutDown** [comment]
Okay sorry my mistake. I read email from drafts folder and he not contained bcc and cc.

**Comment by xXXIMMATTHEWXXx** [comment]
All good :)
