### ISSUE TITLE
HTML body not returning

### ISSUE THREAD

**Issue by MSAyrese** [SSilence/php-imap-client#123]
Hi and thanks for this.

I use "getMessage" method like this to get a specific Email: `$imap->getMessage(2);`
I get many information such as "Plain Message Body" But I can't see "HTML Body".

Please help me that Can I get HTML Body of a email by it's ID.

Thanks a lot.

**Comment by sergey144010** [comment]
Show your $imap->inMessage->message->info.
If there is no html, then it does not exist.

**Comment by sergey144010** [comment]
See the example
https://github.com/SSilence/php-imap-client/blob/master/docs/guide-en/IncomingMessage.md#message-properties

**Comment by sergey144010** [comment]
If the letter contains html. That access to it can be obtained in this way
$imap->incomingMessage->message->html

**Comment by sergey144010** [comment]
Use validation like this
```php
if(isset($imap->incomingMessage->message->html)){};
```

**Comment by MSAyrese** [comment]
Thanks all.
Problem solved.

**Comment by MSAyrese** [comment]
Thanks all.
Problem solved.
