### ISSUE TITLE
Attachment functions running while I don't have any attach in my emails

### ISSUE THREAD

**Issue by MSAyrese** [SSilence/php-imap-client#124]
### If a bug, what happened?

When I Called '$imap->getMessagesByCriteria('ALL', 5, 1);' to get messages (or search), I get this Error Message: `Uncaught Error: Cannot use object of type stdClass as array` that it solved by Issue #93 solution.

After Solving this Problem I get another error in Attachment functions while I don't have any attach in my emails:

`Message: Undefined property: stdClass::$value,
Filename: ImapClient.php,
Line Number: 1380,
Function: getAttachments`

**Backtrace:**
    Line: 1353
    Function: getAttachments
    ----
    Line: 825
    Function: getAttachments
    ----
    Line: 574
    Function: formatMessage
    ----
    Line: 89
    Function: getMessagesByCriteria **(This function called my own PHP file in line 89)**

**AND other error inside it (about Attachments):**

`Type: ImapClientException
Message: Your attachments do not have a name. This should NOT be happening,
Filename: ImapClient.php,
Line Number: 1188,
Function: attachments2name`

**Please notice that I don't have any attach in my emails.**

Please help me to solve. Thanks a lot.

**Comment by hhdivil** [comment]
Any chance you can say what code you're using to produce the error?

**Comment by MSAyrese** [comment]
Hello hhdivil,
I just edited ImapClient class in order to solve problem said in #93 .
Then I called `$imap->getMessagesByCriteria('ALL', 5, 1);` to get first 5 email.

After opening my php file I get this Error:
`Undefined property: stdClass::$value`
`Filename: ImapClient.php`
`Line Number: 1380`
`Function: getAttachments`

**AND**

`Type: ImapClientException`
`Message: Your attachments do not have a name. This should NOT be happening`
`Filename: ImapClient.php`
`Line Number: 1188`
`Function: attachments2name`

**Comment by hhdivil** [comment]
Nevermind I got it.  Line 1381 of ImapClient class:

```php
"name"        => $parameters->value,
```

You must have some weird attachments on that e-mail - maybe it's an image embedded in the signature?

You could always do this between lines 1379 and 1380 and let us know what you get
```php
var_dump($parameters);exit;
```

**Comment by MSAyrese** [comment]
After var_dump($parameters) I get this result:
`object(stdClass)[105]`
`  public 'attribute' => string 'charset' (length=7)`
`  public 'value' => string 'us-ascii' (length=8)`

**Comment by hhdivil** [comment]
ah drop the exit, it'll be the last one in the loop.  sorry my bad

**Comment by hhdivil** [comment]
can you give me the var_dump($part); as well?  might be some interesting info in there - i edited my comment above

**Comment by MSAyrese** [comment]
I realized your edit.
This is result (I wrote "**//--Error**" when Error occurred and I Removed file path).

```
\ImapClient.php:1379:
object(stdClass)[104]
  public 'type' => int 0
  public 'encoding' => int 0
  public 'ifsubtype' => int 1
  public 'subtype' => string 'PLAIN' (length=5)
  public 'ifdescription' => int 0
  public 'ifid' => int 0
  public 'lines' => int 9
  public 'bytes' => int 417
  public 'ifdisposition' => int 0
  public 'ifdparameters' => int 0
  public 'ifparameters' => int 1
  public 'parameters' => 
    array (size=1)
      0 => 
        object(stdClass)[105]
          public 'attribute' => string 'charset' (length=7)
          public 'value' => string 'us-ascii' (length=8)
  public 'disposition' => string 'attachment' (length=10)

\ImapClient.php:1379:
object(stdClass)[105]
  public 'attribute' => string 'charset' (length=7)
  public 'value' => string 'us-ascii' (length=8)

\ImapClient.php:1379:
object(stdClass)[102]
  public 'type' => int 2
  public 'encoding' => int 0
  public 'ifsubtype' => int 1
  public 'subtype' => string 'DELIVERY-STATUS' (length=15)
  public 'ifdescription' => int 0
  public 'ifid' => int 0
  public 'bytes' => int 228
  public 'ifdisposition' => int 0
  public 'ifdparameters' => int 0
  public 'ifparameters' => int 0
  public 'parameters' => 
    object(stdClass)[103]
  public 'disposition' => string 'attachment' (length=10)

\ImapClient.php:1379:
object(stdClass)[103]
//--Error

\ImapClient.php:1379:
object(stdClass)[96]
  public 'type' => int 0
  public 'encoding' => int 1
  public 'ifsubtype' => int 1
  public 'subtype' => string 'PLAIN' (length=5)
  public 'ifdescription' => int 0
  public 'ifid' => int 0
  public 'lines' => int 11
  public 'bytes' => int 844
  public 'ifdisposition' => int 0
  public 'ifdparameters' => int 0
  public 'ifparameters' => int 1
  public 'parameters' => 
    array (size=1)
      0 => 
        object(stdClass)[97]
          public 'attribute' => string 'charset' (length=7)
          public 'value' => string 'UTF-8' (length=5)
  public 'disposition' => string 'attachment' (length=10)

\ImapClient.php:1379:
object(stdClass)[97]
  public 'attribute' => string 'charset' (length=7)
  public 'value' => string 'UTF-8' (length=5)

\ImapClient.php:1379:
object(stdClass)[94]
  public 'type' => int 0
  public 'encoding' => int 1
  public 'ifsubtype' => int 1
  public 'subtype' => string 'HTML' (length=4)
  public 'ifdescription' => int 0
  public 'ifid' => int 0
  public 'lines' => int 272
  public 'bytes' => int 28201
  public 'ifdisposition' => int 0
  public 'ifdparameters' => int 0
  public 'ifparameters' => int 1
  public 'parameters' => 
    array (size=1)
      0 => 
        object(stdClass)[95]
          public 'attribute' => string 'charset' (length=7)
          public 'value' => string 'UTF-8' (length=5)
  public 'disposition' => string 'attachment' (length=10)

\ImapClient.php:1379:
object(stdClass)[95]
  public 'attribute' => string 'charset' (length=7)
  public 'value' => string 'UTF-8' (length=5)
//--Error
```

**Comment by sergey144010** [comment]
getMessagesByCriteria() method now does not work correctly, it has not yet been rewritten. Therefore, you have mistakes.

**Comment by MSAyrese** [comment]
Now, how can I search in mails? @sergey144010

**Comment by sergey144010** [comment]
It uses an outdated method $this->formatMessage($id, $withbody, $embed_images);
It must be replaced by $this->getMessage($id);

**Comment by MSAyrese** [comment]
@SSilence Please solve this problem.

**Comment by sergey144010** [comment]
Wait for replacement or use imap_serch()
http://php.net/manual/en/function.imap-search.php

**Comment by hhdivil** [comment]
make the method private if it does not work?

**Comment by MSAyrese** [comment]
> It uses an outdated method $this->formatMessage($id, $withbody, $embed_images);
> It must be replaced by $this->getMessage($id);

Thanks @sergey144010 

I must do this replace in `getMessagesByCriteria()` function?

**Comment by sergey144010** [comment]
Try this

```php
public function getMessagesByCriteria($criteria = '', $number = 0, $start = 0, $order = 'DESC', $withbody = FALSE, $embed_images = FALSE)
    {
        $emails = array();
        $result = imap_search($this->imap, $criteria);
        if ($number == 0)
        {
            $number = count($result);
        }
        if ($result)
        {
            $ids = array();
            foreach ($result as $k => $i)
            {
                $ids[] = $i;
            }
            $ids = array_chunk($ids, $number);
            $ids = array_slice($ids[0], $start, $number);
            $emails = array();
            foreach ($ids as $id)
            {
                $emails[] =  $this->getMessage($id);
            }
        }
        if ($order == 'DESC')
        {
            $emails = array_reverse($emails);
        }
        return $emails;
    }
```

**Comment by sergey144010** [comment]
And write works or not.

**Comment by MSAyrese** [comment]
Thanks a lot @sergey144010 
It Worked.

Now I noticed When I get a list of emails by `getMessagesByCriteria()` or `getMessages()` the result not said me that this email is in 'Unread' or 'Read' state.

**Comment by sergey144010** [comment]
Letters are considered read.

**Comment by sergey144010** [comment]
Soon I will fix this code.

**Comment by MSAyrese** [comment]
Your mean is in `getMessagesByCriteria('ALL')` function only read state email returned?
When I get emails with this function, I see `Unseen` in header. This specific 'Unread' or 'Read' state?

Another problem: when call `getMessagesByCriteria('ALL')`, all 'unread' emails marked as 'read' without allow.

**Comment by sergey144010** [comment]
OK I will think about it.

**Comment by sergey144010** [comment]
We corrected, update and try a new version.

**Comment by MSAyrese** [comment]
Thanks @sergey144010 
Now, what I must do? Download again?

**Comment by hhdivil** [comment]
if you use composer just type composer update

**Comment by xXXIMMATTHEWXXx** [comment]
@MSAyrese is this still an issue?

**Comment by sergey144010** [comment]
I think can close the topic.

**Comment by xXXIMMATTHEWXXx** [comment]
Yeah.. No response and we have fixed the issue

**Comment by MSAyrese** [comment]
Problem Solved.
