### ISSUE TITLE
Unicode BIG Problem in plain body

### ISSUE THREAD

**Issue by MSAyrese** [SSilence/php-imap-client#127]
I have some emails with unicode encoding. When I try to get plain body of each of them I get an string like this:
`=D9=85=D8=AA=D9=86 =D9=81=D8=A7=D8=B1=D8=B3=DB=8C=20 =D8=A7=D8=B2 =D9=86=D9=88=D8=B9`

I searched in web for a solution to decode/convert this string to unicode/UTF-8 but problem not yet solved.
It's not deference whether emails in HTML format or not. All non-English email (Arabic or Persian Emails) has this problem.

**This problem just in Plain body and HTML body of emails haven't this problem and characters shows normally.**

How can I convert this string to Unicode/UTF-8 characters?
Thanks for your help.

**Comment by xXXIMMATTHEWXXx** [comment]
Are you saying it shows normally in plain or html bodys?

**Comment by xXXIMMATTHEWXXx** [comment]
We do have our `convertToUtf8` function. Try using that and let me know what it does please.

**Comment by sergey144010** [comment]
Show me your $imap->incomingMessage->message->info

**Comment by sergey144010** [comment]
And write a correct result, if possible.

**Comment by MSAyrese** [comment]
> Show me your $imap->incomingMessage->message->info

Everything is OK when I vard_ump($imap->incomingMessage);

I downloaded files again in github and after test now Everything is OK!!!

**Comment by xXXIMMATTHEWXXx** [comment]
Hmmm.. It works now with our latest up to date code?

**Comment by sergey144010** [comment]
Please do `composer update`. Try it. And if everything is okay, we cover the topic.

**Comment by xXXIMMATTHEWXXx** [comment]
@MSAyrese ping

**Comment by MSAyrese** [comment]
> Hmmm.. It works now with our latest up to date code?
Yes.
