### ISSUE TITLE
Getting unread emails

### ISSUE THREAD

**Issue by kurdtpage** [SSilence/php-imap-client#13]
The functions countUnreadMessages() and getUnreadMessages() both use the following code to detect unread emails:
$result = imap_search($this->imap, 'UNSEEN');
My mail server uses the marker 'UNREAD' to mark emails as being not read.

Need to add the following to both functions:
$result = imap_search($this->imap, 'UNREAD');

**Comment by fr0z3nfyr** [comment]
'UNSEEN' flag is the standard.

For your specific case, it'd be just as simple as passing a parameter that defaults to `UNSEEN` and pass your desired `FLAG` like this:
```
getUnreadMessages($flag = 'UNSEEN') {
...
$result = imap_search($this->imap, $flag);    // pass variable instead of string constant
...
}
```
and call like so: `getUnreadMessages('UNREAD')`

**Comment by xXXIMMATTHEWXXx** [comment]
I will submit this into a new pr. Thanks

**Comment by kurdtpage** [comment]
Thanks
