### ISSUE TITLE
Deleting incoming messages

### ISSUE THREAD

**Issue by hhdivil** [SSilence/php-imap-client#130]
While looping over incoming messages, calling the deleteMessage() function doesn't appear to work - the message is still there the next time.  Also there's no way to get the ID of a message from the IncomingMessage object.

```php
$messages = $imap->getMessages();
foreach ($messages as $message)
{
    $imap->deleteMessage($message->id); // had to make the id property public to do this
}
```

**Comment by hhdivil** [comment]
OK I figured it out - you have to use the "uid" not the "id" to delete a message - but the "uid" property on the IncomingMessage object was null, so you have to do the following which is weird really:

```php
$uid = $imap->getUid($message->id);
$imap->deleteMessage($uid);
```

Shouldn't there just be a deleteMessage() function on the IncomingMessage class itself?

**Comment by xXXIMMATTHEWXXx** [comment]
So this deleteMessage would 1) Delete the message from the inbox 2) Null the object correct?

**Comment by sergey144010** [comment]
Message id is obtained this way
```php
$inMessages = $imap->getMessages();
foreach ($inMessages as $inMessage)
{
# id
    $inMessage->header->msgno;
# uid
    $inMessage->header->uid;
}
```

See http://php.net/manual/ru/function.imap-fetch-overview.php
Id in IncomingMessage must be private, therefore.
You can also use method
```php
$imap->getUid($id);
```

But we'll think about this.
```php
$imap->deleteMessage($uid);
```

This should be added to the documentation.
```php
# id
    $inMessage->header->msgno;
```

**Comment by xXXIMMATTHEWXXx** [comment]
Hello @hhdivil, Is this still an issue. Please close this issue if so.

**Comment by xXXIMMATTHEWXXx** [comment]
@hhdivil I assume this issue is fixed. Closing...
