### ISSUE TITLE
No Attachments in $imap->IncomingMessage while the Email have attachment

### ISSUE THREAD

**Issue by MSAyrese** [SSilence/php-imap-client#134]
### You can see I have a attach in my email:

![](https://cloud.githubusercontent.com/assets/20723864/24958426/7fd5d24e-1fa4-11e7-9e30-276abf80744b.png)

### But in the returned data in $imap->IncomingMessage I can't see any information about it:

![](https://cloud.githubusercontent.com/assets/20723864/24958478/a5cc5d42-1fa4-11e7-9463-d4c20668f9bf.png)

## How can I solve this problem?

**Comment by sergey144010** [comment]
Have you updated the code?

**Comment by sergey144010** [comment]
Now there is no attachment,  but is attachments

**Comment by sergey144010** [comment]
```php
    $imap->getMessage(9);
    var_dump($imap->incomingMessage->attachments[0]->info->structure->bytes);
```

**Comment by sergey144010** [comment]
```php
    var_dump($imap->incomingMessage->attachments[0]->name);
    var_dump($imap->incomingMessage->attachments[0]->body);
```

**Comment by MSAyrese** [comment]
> Have you updated the code?
Yes.

> var_dump($imap->incomingMessage->attachments[0]->info->structure->bytes);
It haven't 'attachments' property.
It have 'attachment' property (it is NULL).

**Comment by sergey144010** [comment]
You are using the old version of the code, do
```php
composer update
```
Now, for example see there https://github.com/SSilence/php-imap-client/blob/master/docs/guide-en/IncomingMessage.md#attachments-properties

**Comment by MSAyrese** [comment]
@sergey144010 I updated Now.
But I still have the issue.

**Comment by sergey144010** [comment]
show me your
```php
 $imap->getMessage(9);
 var_dump($imap->incomingMessage);
```

**Comment by MSAyrese** [comment]
@sergey144010 
This Is a screen shot of var_dump of incomingMessage:

![mailbox-test](https://cloud.githubusercontent.com/assets/20723864/24977025/f2ebe908-1fe0-11e7-96ea-9c84d3cf2c11.jpg)

**Comment by sergey144010** [comment]
Well, it's better. Now show
```php
var_dump($imap->incomingMessage->structure->parts);
```

**Comment by MSAyrese** [comment]
> var_dump($imap->incomingMessage->structure->parts);

![mailbox-test](https://cloud.githubusercontent.com/assets/20723864/25020939/8b44930c-20a5-11e7-9b80-f94dfd401657.jpg)

**Comment by sergey144010** [comment]
Ok, now
```php
var_dump($imap->incomingMessage->structure->parts[0]->parts);
# and
var_dump($imap->incomingMessage->structure->parts[1]->dparameters);
# and
var_dump($imap->incomingMessage->structure->parts[1]->parameters);
```
For a faster and more detailed study, it would be good to do `php scripMail.php > debug.txt` and lay it out in any cloud. And delete important information for you. And give a link to the file. if it is possible.

**Comment by MSAyrese** [comment]
> For a faster and more detailed study, it would be good to do php scripMail.php > debug.txt (var_dump($imap->incomingMessage)) and lay it out in any cloud. And delete important information for you. And give a link to the file. if it is possible.

I'm using [CodeIgniter](https://codeigniter.com) and it's not able to do `php scripMail.php > debug.txt `

Here is 3 screen shot of var_dump.

In `var_dump($imap->incomingMessage->structure->parts[1]->parameters);` and `var_dump($imap->incomingMessage->structure->parts[1]->dparameters);` I can see my attachment name (attachment name: site@******.com.mobileconfig).

At the end of result of `var_dump($imap->incomingMessage->structure->parts[0]->parts);`  I can see images included in email.

![mailbox-test](https://cloud.githubusercontent.com/assets/20723864/25039970/e3a2d722-211b-11e7-8d2e-4395a867501e.jpg)

![mailbox-test 2](https://cloud.githubusercontent.com/assets/20723864/25039974/e948b818-211b-11e7-809e-39f6791514c9.jpg)

![mailbox-test 1](https://cloud.githubusercontent.com/assets/20723864/25039978/eeffcc88-211b-11e7-8dc0-cf6afc4061b0.jpg)

**Comment by sergey144010** [comment]
Ok, then
```php
var_dump($imap->getSection($id, '1.2'));
```

**Comment by TrueShutDown** [comment]
I don't know it will be helpful, but debugger and var_dump have some limits and sometimes not show long content. 

in php.ini
```
xdebug.var_display_max_depth = 5
xdebug.var_display_max_children = 256
xdebug.var_display_max_data = 1024 
```

for show full output I recommend using this code:
`file_put_contents('debug.txt', print_r($array, true))`
or
`file_put_contents('debug.txt', print_r($array, true), FILE_APPEND)`

**Comment by tonym65** [comment]
Hello i had the same problem and i changed this code:
private function getRecursiveSections($obj, $recursive = 1)
    {                        
        $this->section .= $recursive.';';              
        if(!isset($obj->parts)){
            return;
        };        
        foreach($obj->parts as $key => $subObj){                        
            echo 'drinne '.$zahler;            
            echo '</br>';
            if($key != 0){
                $this->section .= $recursive.'.'.$key.';';
            };
            //var_dump($this->section);
            //echo '</br>';
            //var_dump($subObj);
            $this->getRecursiveSections($subObj, $recursive+1);            
        };       
    }
to this code:
private function getRecursiveSections($obj, $recursive = 1)
    {                        
        for($i=1; $i <= $this->countAttachment+1; $i++) {
          $this->section .= $i.';'; 
        }
        echo $this->section;
        return;                      
    }
and now it works for me i hope this helps you too.

**Comment by tonym65** [comment]
filename: IncomingMessage.php

**Comment by MSAyrese** [comment]
Thanks @tonym65 
But it not worked for me.

**Comment by TrueShutDown** [comment]
Ok and are you sure display_max_data is bigger than your attachment? Try to set 
`xdebug.var_display_max_data = -1`
or better show data from
`file_put_contents('debug.txt', print_r($array, true))`

**Comment by sergey144010** [comment]
Show me
```php
var_dump($imap->getSection($id, '1.2'));
```

**Comment by MSAyrese** [comment]
Result of `php var_dump($imap->getSection($id, '1.2'));`
![mailbox-test 3](https://cloud.githubusercontent.com/assets/20723864/25070743/263b645e-22bc-11e7-96b6-338803805fca.jpg)

**Comment by sergey144010** [comment]
now
```php
var_dump($imap->getSection($id, '2'));
```
and immediately
```php
var_dump($imap->getSection($id, '1'));
var_dump($imap->getSection($id, '1.1'));
```

**Comment by sergey144010** [comment]
You probably have a Xdebug php.ini. Like this:
```ini
[Xdebug]
zend_extension=path\to\php_xdebug-2.3.3-5.4-vc9-x86_64.dll
xdebug.remote_enable=1
xdebug.remote_host=localhost
xdebug.remote_port=9000
```
If this is commented out and the server is rebooted, then a full dump will be output.

**Comment by sergey144010** [comment]
@MSAyrese try changing the method getRecursiveSections() as below. And write the result.
```php
    private function getRecursiveSections($obj, $recursive = 1)
    {
        $this->section .= $recursive.';';
        if(!isset($obj->parts)){
            return;
        };
        foreach($obj->parts as $key => $subObj){
### Here to comment out IF and add $key+1  as below
            #if($key != 0){
                $this->section .= $recursive.'.'.($key+1).';';
            #};
### 
            $this->getRecursiveSections($subObj, $recursive+1);
        };
    }
```

**Comment by MSAyrese** [comment]
changing getRecursiveSections not solved problem. result is like first post of this issues.

**Comment by xXXIMMATTHEWXXx** [comment]
@sergey144010 ping. Can you continue to help with this issue?

**Comment by sergey144010** [comment]
I can, but based on what he writes, I understand that he is afraid that his code will be broken. The only thing I can advise him is to install it in another directory (`composer require ssilence/php-imap-client dev-master`), go to the 'tests' folder, open 'template.php', write down the code for receiving the message and getting the attachment, like this.
```php
$imap->getMessage(9);
# show
var_dump(count($imap->incomingMessage->structure->parts));
var_dump($imap->incomingMessage->section);
```
And if it's okay to update.

And if it is not normal to continue to understand the problem together without insults. Maybe he thinks we get paid for this? Or maybe he himself offered at least some pull requests?

**Comment by xXXIMMATTHEWXXx** [comment]
@MSAyrese I would say make a new duplicate environment and once you have the duplicate working copy it over.

**Comment by xXXIMMATTHEWXXx** [comment]
@MSAyrese is this still an issue?

**Comment by MSAyrese** [comment]
@xXXIMMATTHEWXXx I decided to Completely delete your hooey library from my project and use an other library.

**Comment by xXXIMMATTHEWXXx** [comment]
Dont matter to me. Or anyone. We all like to eat and have jobs to worry
about. I also have physical injuries restricting me. Sorry bud we all gotta
keep ourselves up first
