### ISSUE TITLE
Can't move message to another mailbox

### ISSUE THREAD

**Issue by filipefreitas82** [SSilence/php-imap-client#136]
Here is the test code:

`echo "Searching...".PHP_EOL;

$emails = $this->imap->getMessagesByCriteria('FROM "me@test.test"');

print_r('Searh result: ' . count($emails) .PHP_EOL);

/** @var IncomingMessage $email */
foreach($emails as $email) {
        if($this->imap->moveMessage($email->header->uid, 'test'))
                echo "Move successesfull!".PHP_EOL;
        else
                echo "Move failed!".PHP_EOL;
}`

Here is the output:

> Connected!
> Searching...
> Searh result: 1
> Move failed!

I get a valid message uid but the moveMessage method keeps returning false.

Is there something I'm missing?
Thanks.

**Comment by sergey144010** [comment]
You need specify a mailbox as [Gmail]/Test or INBOX.Test
Try getFolders(null, 2) and look at the folder.

**Comment by sergey144010** [comment]
```php
    $imap->getMessage(10);
    if($imap->moveMessage($imap->incomingMessage->header->uid, 'INBOX/no_ping')){
        echo 'OK';
    }else{
        echo 'FAIL';
    };
```

**Comment by filipefreitas82** [comment]
Thats it. Forgot the INBOX.
Thanks sergey
