### ISSUE TITLE
Do I need to include the phpDocumentor documentation in the repository?

### ISSUE THREAD

**Issue by sergey144010** [SSilence/php-imap-client#143]
Do I need to include the phpDocumentor documentation in the repository?
Documentation is generated automatically. 
https://github.com/phpDocumentor/phpDocumentor2
I now have more than 20 folders and files to them.
Can compress into the archive?
Or just give a link in our documentation?
Install
```php
$ composer require --dev phpdocumentor/phpdocumentor
```
Use
```php
$ phpdoc run -d <SOURCE_DIRECTORY> -t <TARGET_DIRECTORY>
```

**Comment by xXXIMMATTHEWXXx** [comment]
Yes. Both. We need to have our copy which will only be updated when major changes are made and users can have their own

**Comment by sergey144010** [comment]
What type of archive should I create? zip, rar or other?

**Comment by xXXIMMATTHEWXXx** [comment]
zip becuase it is most common
