### ISSUE TITLE
Notice:  Undefined property: stdClass::$dparameters

### ISSUE THREAD

**Issue by JerBlo** [SSilence/php-imap-client#149]
In some e-mails, an inline attachment does not have the "dparameters" array for the filename of the image (e-mail was sent from Outlook 2016). 

This result in a PHP notice and warning (and off course no filename).

> Notice:  Undefined property: stdClass::$dparameters in ...\ImapClient\IncomingMessageAttachment.php on line 70
>Warning:  Invalid argument supplied for foreach() in ...\ImapClient\IncomingMessageAttachment.php on line 70

Possible solution:
- Check with ifdparameters if the "dparameters" array exists
- Add fallback on "parameters"

In code this looks like: https://pastebin.com/NchXGGsg

**Comment by xXXIMMATTHEWXXx** [comment]
Hmm, we will be sure to add a fallback!! I'm pretty sure the latest pr fixed but let me know!
