### ISSUE TITLE
Request: make all private functions protected

### ISSUE THREAD

**Issue by JerBlo** [SSilence/php-imap-client#150]
I would like to have the ability to extend the php-imap-client files, for adding some custom needs (parsing an attached e-mail as inline text and build an array with sections (key) and plain/html/attachments-types (values).

However, extending the class works great, but you are not able to overrule private functions. If it's possible to change them to protected functions, the extended class can overrule some logic, without the need of implementing all 'parent' methods.

**Comment by sergey144010** [comment]
Which classes do you want to expand? Because the idea is dangerous, because you can break the logic. Our need to think about this or add interfaces.

**Comment by xXXIMMATTHEWXXx** [comment]
I think it would be best to add an overrides folder. Somehow impelment that
kind of how prestashop does it.

**Comment by JerBlo** [comment]
In my case I needed to extend IncomingMessage for several reasons:

1.  Changed the getRecursiveSections() function for embedded e-mail attachments (we want to see them as a forwarder mail): 

> // Custom code for getting correct sections for embedded e-mail attachment
			if($subObj->type == 2)
			{
				$subObj = $subObj->parts[0];
			}

2. Changed the getObjectStructureFromParts() function, for subtypes RFC822 (e-mail attachments), since section/part numbers should be build a bit different then.
>// Custom code for getting correct sections for embedded e-mail attachment
		if($inObject->subtype == 'RFC822') 
		{
			$inObject = $inObject->parts[0];
		}


3. Extended getBody and getAttachments and stores an array with section number related to HTML/PLAIN or Attachment item. (Apple mail will send inline images as different sections: HTML, IMAGE, HTML, IMAGE, HTML)

Because of above, we needed to extend ImapClient also and redefine the methods which load a new IncomingMessage object.

**Comment by xXXIMMATTHEWXXx** [comment]
@sergey144010 what do you think about adding an override folder somewhat like prestashops?

**Comment by JerBlo** [comment]
Could be an option, as long as each method-call also checks in the extended/custom code, otherwise it will not solve the problem with calling private methods from other methods in that (extended) class.

**Comment by xXXIMMATTHEWXXx** [comment]
True

**Comment by sergey144010** [comment]
@JerBlo 
1. 
> Changed the getRecursiveSections() function for embedded e-mail attachments (we want to see them as a forwarder mail):

Now the meaning of this function is this:
```php
structure->
 ...
 parts = [
  ...
   parts = [...]
  ...
 ...
]
...
```
There is a recursive search for ...->parts[]. And set section like this [1, 1.1, 2, 2.1, 2.2]

2. About subtypes RFC822
Need just add this in TypeBody or TypeAttachments.

**Comment by sergey144010** [comment]
Maybe need make this, you can show more of the working code that you use.

**Comment by sergey144010** [comment]
Only  IncomingMessage class ?

**Comment by sergey144010** [comment]
Or you can do this as follows, you make all the changes you want and do PullRequest in the DEV branch, then we'll look and test all the changes and if all is good then we'll take them. BUT @xXXIMMATTHEWXXx need update DEV branch up to today's state.

**Comment by xXXIMMATTHEWXXx** [comment]
I believe I can't because someone uses it because there is a problem with the current version?

**Comment by sergey144010** [comment]
All serious problems have already been eliminated. Or what do you mean? A branch dev is just now with old mistakes.
And in general the meaning of branches:
Dev - for development, master - current stable, ...  and next releases

**Comment by sergey144010** [comment]
I think that you need to make a reference point on the current code, because there the code is cleaned and more or less without errors, because before that there was a lot of unnecessary and not working.

**Comment by sergey144010** [comment]
To wait a month and if there will be no serious problems to do release. And new code to will do in dev branch and to transfer stable in the master branch.

**Comment by xXXIMMATTHEWXXx** [comment]
I was trying to say I thought there was an issue that used the old branch. Was that fixed?

**Comment by sergey144010** [comment]
I did PullRequests only in master branch, 
When you branch out a project, then several copies of it (branches) are created. Correspondingly, if you make corrections only in one branch, then others will remain untouched.

**Comment by xXXIMMATTHEWXXx** [comment]
This has been fixed
