### ISSUE TITLE
Undefined property: stdClass::$types

### ISSUE THREAD

**Issue by lhidalgo42** [SSilence/php-imap-client#151]
in some emails fail to decode body in types property

 ...\ssilence\php-imap-client\ImapClient\IncomingMessage.php
    /**
     * Decode body
     *
     * @return void
     */
    private function decodeBody()
    {
        foreach ($this->message->types as $typeMessage) {
 
            switch ($this->message->$typeMessage->structure->encoding)
.
.
.
maybe a solution to this issue is add an exception

**Comment by sergey144010** [comment]
If the error pops up, write it here.
Also you can turn off the decoding.
```php
getMessage($id, $decode = IncomingMessage::NOT_DECODE)
```

**Comment by xXXIMMATTHEWXXx** [comment]
Do note I plan to rename the NOT_DECODE to NODECODE. Still use NOT_DECODE
though

**Comment by xXXIMMATTHEWXXx** [comment]
@ibpavlov is this still an issue?

**Comment by ibpavlov** [comment]
I had a different issue.

**Comment by xXXIMMATTHEWXXx** [comment]
Sorry. Wrong tag @lhidalgo42

**Comment by xXXIMMATTHEWXXx** [comment]
I believed this issue has been fixed with our latest updates. Closing. Comment back if this is still an issue.
