### ISSUE TITLE
$imap->incomingMessage not working.

### ISSUE THREAD

**Issue by abdullahseba** [SSilence/php-imap-client#152]
Hi (again) :)
`$emails = $imap->incomingMessage;` retuns NULL.
And `$imap->incomingMessage->header`  has an error `Notice: Trying to get property of non-object`
I need something a bit faster than ` $imap->getMessages()`

**Comment by sergey144010** [comment]
What actions do you do before that?
```php
$imap->incomingMessage;
```
$imap->incomingMessage returns the IncomingMessage object of after using the method of $imap->getMessage($id).

**Comment by abdullahseba** [comment]
`Fatal error: Uncaught Error: Call to undefined method SSilence\ImapClient\ImapClient::incomingMessage()`
```
$imap->selectFolder("inbox");
$imap->incomingMessage(2);
$emails = $imap->incomingMessage->header;

**Comment by abdullahseba** [comment]
Is there something faster than ` $imap->getMessages()`? It retuns evrything about the email when all I need is the header for the list of emails in the client.

**Comment by sergey144010** [comment]
1. 
@abdullahseba Where did you get this from?
```php
$imap->incomingMessage(2); //line 28
```
Can be in the documentation?

2.

> Is there something faster than $imap->getMessages()? It retuns evrything about the email when all I need is the header for the list of emails in the client.

There is a way. It is necessary to extend the ImpatClient class, take $imap property there and do imap_headers().
http://php.net/manual/ru/function.imap-headers.php

**Comment by abdullahseba** [comment]
its retuns only two emails then
>getMessages($number, $start, $order

**Comment by sergey144010** [comment]
And how many letters are there?

**Comment by abdullahseba** [comment]
u mean emails?

**Comment by sergey144010** [comment]
You read
> its retuns only two emails then
    getMessages($number, $start, $order)

Should it be 20?

**Comment by abdullahseba** [comment]
Yeah!
`$imap->incomingMessage(2)` retuns 2 emails
`$imap->incomingMessage()` retuns all 20 emails.

**Comment by sergey144010** [comment]
$imap->incomingMessage - it is OBJECT for ONE last message which get using methods getMessage() or getMessages().

**Comment by abdullahseba** [comment]
????

**Comment by sergey144010** [comment]
And this
```php
$imap->incomingMessage(2)
# or
$imap->incomingMessage()
```
It is not right.
And this right
```php
$imap->incomingMessage
```

**Comment by sergey144010** [comment]
!!!

**Comment by sergey144010** [comment]
Read documentation please.

**Comment by sergey144010** [comment]
https://github.com/SSilence/php-imap-client/blob/master/docs/guide-en/IncomingMessage.md

**Comment by abdullahseba** [comment]
Woops sorry getting muddled with with `$imap->incomingMessage()` and `$imap->incomingMessages()`
so `$imap->incomingMessage(2)` should return the second email but does not.

**Comment by sergey144010** [comment]
Not
> second email

but mail with $id = 2;
You have message with id = 2 ?

**Comment by abdullahseba** [comment]
oh so the id is not the mail order number?

**Comment by abdullahseba** [comment]
where is the mail id? i can see a `uid`

**Comment by sergey144010** [comment]
You can make this
```php
$array = $imap->getBriefInfoMessages();
foreach($array as $message){
# This Id message
 print $message['id'];
};
```
OR
```php
$array = $imap->getMessages();
foreach($array as $message){
# This Id message
 print $message->header->msgno;
};

```

**Comment by sergey144010** [comment]
Or try use http://php.net/manual/ru/function.imap-headers.php

**Comment by abdullahseba** [comment]
yep works so not an error shall I close?

**Comment by sergey144010** [comment]
Still have questions about this? If not, close it.
