### ISSUE TITLE
Who's doing what

### ISSUE THREAD

**Issue by sergey144010** [SSilence/php-imap-client#154]
In order not to do the same job twice, I suggest writing who is doing what now.

**Comment by sergey144010** [comment]
I'm currently working on testing.

**Comment by xXXIMMATTHEWXXx** [comment]
I am doing cleanup and documentation. Us two can split stuff as we go unless anyone wants to help aswell

**Comment by alepeino** [comment]
Good thing you said this, I was about to start on testing as well.

Also, can we integrate some coding style CI tool? (Like [StyleCI](https://styleci.readme.io/docs/getting-started) ) It will make further contributions easier.

**Comment by xXXIMMATTHEWXXx** [comment]
I think that. I am talking to the repo owner about this

**Comment by xXXIMMATTHEWXXx** [comment]
@alepeino Style CI has been implemented.

**Comment by xXXIMMATTHEWXXx** [comment]
I am also getting travis added atm
