### ISSUE TITLE
Fatal Error...

### ISSUE THREAD

**Issue by latkinson** [SSilence/php-imap-client#155]
### Feature request or bug
Bug
### If a bug, what did you expect to happen?
echo a string
### If a bug, what happened?
fatal error
### If a bug, list steps to reproduce bugs.
This happens for me with emails that do not have any Section::_body content in inMess->messages->plain.
var_dump shows it as FALSE:

["_body":"SSilence\ImapClient\Section":private]=>bool(false)

but since it is private, I can't know that. Then, Section::__toString() cannot handle booleans.

One thing I did notice that seems like it might be an issue is that Section::__isset() is the same code as Section::__get(). It's not checking if anything is set...

### If a bug, did you do these steps?
[y] Download and use the lastest stable version
[y] See if the issue has already been reported
[n] Debug

**Comment by xXXIMMATTHEWXXx** [comment]
Hnmm, we seem to have a problem with null checks. Thank you for reporting this

**Comment by xXXIMMATTHEWXXx** [comment]
Also will you show the code your using

**Comment by sergey144010** [comment]
@latkinson You mean you're doing something like this?
```php
# it work
$imap->getMessage($id);
# here error
echo $imap->incomingMessage->messages->plain;
```
or
```php
# it work
$emails = $imap->getMessages();
# here error
json_encode($emails);
```
right?

**Comment by latkinson** [comment]
echo $imap->incomingMessage->messages->plain;
is what does it, yes. I haven't tried popping it to json.

**Comment by latkinson** [comment]
This is my code:
`
$message='';

// Has the "plain" field set, but the value is (bool)false.
// While it is set, being private, I can't
if (isset($email->message->plain)) { // returns true
    $message = $email->message->plain;
} else if (isset($email->message->html)) {
    $message = $email->message->html;
}

// Shows fine
var_dump($message);

// Fails: Section::_body is (bool)false, but __toString MUST return a string...
//  - "Catchable fatal error: Method SSilence\ImapClient\SubtypeBody::__toString() must return a string value"
echo $message;
`
Is there some other way I should be accessing the message content? Check for message->html first, then clean it?

**Comment by latkinson** [comment]
Wait, yes, checked the update. That works great.
Thanks!

**Comment by sergey144010** [comment]
They have not yet taken PullRequest, but do you already work??
