### ISSUE TITLE
HTML Message without content

### ISSUE THREAD

**Issue by MrRoudeLeiw** [SSilence/php-imap-client#157]
Hey guys, 
I just took a look at your imap-client and so far I really like it, but for some messages I'm just able to get the message in plain text form and not in HTML form.
Have a nice day

**Comment by xXXIMMATTHEWXXx** [comment]
What exactly do you mean some messages? How do they defer from others? Can you show relevant code?

**Comment by sergey144010** [comment]
This does not fit?
```php
$imap->incomingMessage->messsage->plain
# or
$imap->incomingMessage->messsage->text
```

**Comment by MrRoudeLeiw** [comment]
I'm using 
`$emails = $imap->getMessages();`
`$message = $email->message->html.PHP_EOL;`
For the most emails I can't get the message as HTML.

**Comment by xXXIMMATTHEWXXx** [comment]
Hmm. Are those messages html? Show the var_dump of the message

**Comment by MrRoudeLeiw** [comment]
I just double checked it, the message is not html. So is there any possibility to format the message?

**Comment by sergey144010** [comment]
The allowed message formats are located here - TypeBody.
You can see which message types are separated in this way - ```var_dump($imap->incomingMessage->message-> types)```.
To implement formatting, from what type to what type?

**Comment by sergey144010** [comment]
If this is not present, then there are no such parts in the message.
`
$imap->incomingMessage->messsage->plain
$imap->incomingMessage->messsage->html
`
Or there are no such types here TypeBody

**Comment by xXXIMMATTHEWXXx** [comment]
@MrRoudeLeiw is this still an issue?

**Comment by MrRoudeLeiw** [comment]
Everything Fine so far.

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks
