### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by alfonsobries** [SSilence/php-imap-client#159]
### Feature request or bug
Bug

### If a bug, what did you expect to happen?
The documentation page doest work

### If a bug, what happened?
When you open the documentation you can see the menu, but doesn't load the documentation, in chorme dev tools i have this error:
Failed to load resource: the server responded with a status of 404 (Not Found) /docs/guide/gettingstarted.md

### If a bug, list steps to reproduce bugs.
Open the documentation: http://ssilence.github.io/php-imap-client/gettingstarted.html

**Comment by xXXIMMATTHEWXXx** [comment]
Sorry this was my fault. I have fixed this *facepalm*

**Comment by filipefreitas82** [comment]
Documentation is still down?
Can't access any of the docs.

**Comment by alfonsobries** [comment]
Seems that is still down

**Comment by anielka** [comment]
this may help as a workaround:
https://github.com/SSilence/php-imap-client/tree/master/docs/guide
bon apetite :D

**Comment by xXXIMMATTHEWXXx** [comment]
Yeah. I may change all the documentation links to use the static ones from
github
