### ISSUE TITLE
SubtypeBody:class 

### ISSUE THREAD

**Issue by anielka** [SSilence/php-imap-client#162]
### Feature request or bug
bug
### If a bug, what did you expect to happen?
list messages
### If a bug, what happened?
1. PHP Parse error:  syntax error, unexpected ':', expecting ')' in /ImapClient/IncomingMessage.php on line 362
after fixing code SubtypeBody:class -> SubtypeBody::class  we goes to
2. PHP Fatal error:  Cannot access empty property in /ImapClient/IncomingMessage.php on line 366
with i can't solve myself
### If a bug, list steps to reproduce bugs.

- download current master
- edit /ImapClient/IncomingMessage.php on line 362
- configure (with gmail)
- use $imap -> getMessages();
- 

### If a bug, did you do these steps?
[] Download and use the lastest stable version TRUE
[] See if the issue has already been reported NOT REPORTED (on my search-fu is on really low level)

//edit wrong error pasted :)

**Comment by xXXIMMATTHEWXXx** [comment]
Thank you! Travis recently cought this I'm working to fix it.thank you!

**Comment by anielka** [comment]
that's great. sorry for offtopic, but two questions:
1. why only one branch and not two? (_current working_ mastar && wip dev)
2. with commit should work for this moment (i had to fallback to oldie, one file wrapper - yeap i know, shame on me, but tommorow early morning i have to present working solution)

PS. I think you're doing a great job. keep coding :)

**Comment by xXXIMMATTHEWXXx** [comment]
Thank you!
To anwser your questions:
1) We are still working on getting branches integrated. :(
2) No problem. Any help is always welcome!

**Comment by xXXIMMATTHEWXXx** [comment]
Hey, would you mind updating and showing me the new error?

**Comment by anielka** [comment]
sure, no prob, but later today. in couple of hours i'll find some time to do that :)

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks!

**Comment by xXXIMMATTHEWXXx** [comment]
Hey.... Is this still an issue?

**Comment by anielka** [comment]
hello there. no, it's work correct right now
excuse me my absence - health issures ;/

**Comment by mkhimself** [comment]
Fatal error: Cannot access empty property in /application/libraries/ImapClient/IncomingMessage.php on line 366

Did this ever get resolved? Am I doing something wrong?

**Comment by anielka** [comment]
if working on plain php then you have to include all package files, not only those from example. 
btw. hello again, the best option is to edit docs and add "full include block". that will eliminate this error and propably future questions about it. for now I have no idea what is requested, so i require_once everything :)

**Comment by mkhimself** [comment]
Im using codeigniter, Its been fourteen days and Ive completely forgot what the issue was, but no matter i resolved it somehow. No worries
