### ISSUE TITLE
Some PHP error in the latest version while using getMessages()

### ISSUE THREAD

**Issue by abdullahseba** [SSilence/php-imap-client#163]
Hi again :)
I just update my projects dependences with composer and now `getMessages` is returning this: 
```
[14-May-2017 23:53:35 Europe/London] Slim Application Error:
Type: ParseError
Message: syntax error, unexpected ':', expecting ')'
File: C:\xampp\htdocs\uf4.0.8\app\vendor\ssilence\php-imap-client\ImapClient\IncomingMessage.php
Line: 362
```
A typo maybe?

**Comment by xXXIMMATTHEWXXx** [comment]
Thank you! We seem to have an issue with array declaration. Will look
further into this

**Comment by xXXIMMATTHEWXXx** [comment]
@abdullahseba what is the latest commit you recall where this worked?

**Comment by abdullahseba** [comment]
Idk :( I just updated my project and this happend to be part of it.

**Comment by xXXIMMATTHEWXXx** [comment]
Okay, what version did you have before you updated?

**Comment by abdullahseba** [comment]
No idea I just run composer without looking

**Comment by abdullahseba** [comment]
https://github.com/SSilence/php-imap-client/commit/8412814ebe13737dbbd337916a1b9d30f2cadf18 ?

**Comment by abdullahseba** [comment]
`Parse error: syntax error, unexpected ':', expecting ')' in C:\xampp\htdocs\mail2\vendor\ssilence\php-imap-client\ImapClient\IncomingMessage.php on line 362`

**Comment by abdullahseba** [comment]
line number matches

**Comment by xXXIMMATTHEWXXx** [comment]
Let me undo that commit and see. I was attempting to fix travis

**Comment by xXXIMMATTHEWXXx** [comment]
I have reverted that commit. Let me know

**Comment by abdullahseba** [comment]
`$travisIsABaby` LOOOOL xD

**Comment by abdullahseba** [comment]
ok

**Comment by abdullahseba** [comment]
WORKS!

**Comment by xXXIMMATTHEWXXx** [comment]
Hmmm. It works but Travis detects a syntax error. I will continue to look into this. May this issue be closed?

**Comment by abdullahseba** [comment]
yes
