### ISSUE TITLE
Documentation: Some .md files are missing

### ISSUE THREAD

**Issue by usolved** [SSilence/php-imap-client#165]
### Feature request or bug
Bug

### If a bug, what happened?
Several topics of the documentation can't be accessed. For example Getting started, Connecting, Error database, Installing, ...

### If a bug, list steps to reproduce bugs.
Example:
When clicking on http://ssilence.github.io/php-imap-client/gettingstarted.html it tries to load gettingstarted.md as Ajax request. But the file is not found on the server and returns a 404.

**Comment by xXXIMMATTHEWXXx** [comment]
Thank you I will look into fixing this

**Comment by xXXIMMATTHEWXXx** [comment]
I have fixed this :)

**Comment by usolved** [comment]
Thanks :)
