### ISSUE TITLE
Why are the docs blank?

### ISSUE THREAD

**Issue by abdullahseba** [SSilence/php-imap-client#167]
The new docs have been blank for some time now. I think the old ones should be kept till the new one isfinished.

**Comment by xXXIMMATTHEWXXx** [comment]
I am working on fixing it. Due to a physical injury, I haven't really been on key with it.

**Comment by abdullahseba** [comment]
Sorry to hear it hope you get better.

**Comment by xXXIMMATTHEWXXx** [comment]
Me too! I have begun the update!

**Comment by xXXIMMATTHEWXXx** [comment]
All good. I have pushed. Getting started somehow is acting weird but it may just be cached.
