### ISSUE TITLE
No support for prefixed folders.

### ISSUE THREAD

**Issue by basdog22** [SSilence/php-imap-client#17]
Many cpanel hosts have their imap folders prefixed. For example my server folder's names are:

INBOX.Sent
INBOX.Trash
etc

It would be good to add a public class property named prefix or something and use this on getTrash,getSent etc.

**Comment by xXXIMMATTHEWXXx** [comment]
@basdog22  I may add this a pr soon :) Thanks for the suggestion

**Comment by natanfelles** [comment]
Please, add "New Feature" label or anything like...

**Comment by sergey144010** [comment]
So, I think need create new branch for testing new features.
Maybe name new branch - newFeatures.
And I am already ready to give to the test this possibility.
Because it is necessary to discuss.

**Comment by sergey144010** [comment]
I make this:
`$imap->getFolder_INBOX_Fridman();`
case-sensitive letters

**Comment by xXXIMMATTHEWXXx** [comment]
I think the better thing to do is this:
`$imap->getSent($prefix = "")` and let the devs set it. Same for getTrash etc. But i like the idea. Mine would only make it smaller

**Comment by sergey144010** [comment]
If I do so:
`$imap->getSent()`
If there is a mistake in the title of the folder.
`$imap->getSeMnt()`
or just write an erroneous method with `get`
that will happen to the server error connect.
It was therefore added `getFolder`. To avoid ambiguity.
And the folder at the top level can be called not INBOX and another for example MYINBOX. How will the work method `$imap->getSent()` ? Need as min `$imap->getMyinboxSent()`.
My prefix Server INBOX/Sent etc. `/`. Make it mutable without problems.
And one problem case-sensitive letters on server. Your server understands `inbox/sent` (lowercase letters) ?
What do you think about this?

**Comment by xXXIMMATTHEWXXx** [comment]
Hmmm I dont know atm. I would play around with a few ideas

**Comment by sergey144010** [comment]
I have pull request, for my idea, but I don't want make pull request in master branch.

**Comment by xXXIMMATTHEWXXx** [comment]
Hmmm. I dont want to do this without @SSilence 
Lets see what he says. I say we go ahead and make a test branch.

**Comment by natanfelles** [comment]
Is not possible get messages selecting a folder like?

```php
$imap->selectFolder('INBOX.Sent')
```
I think that a param `$pattern` must be added to the method `getFolders()` then will be possible to get child folders, like @basdog22 say.

Example:

```php
public function getFolders($pattern = '*') {    
    $folders = imap_list($this->imap, $this->mailbox, $pattern);
    return str_replace($this->mailbox, "", $folders);
}
```

* I have not tested it yet.

**Comment by natanfelles** [comment]
In this way:

```php
$imap->getFolders('INBOX')
```

will return the child folders of `INBOX` and if `INBOX` has an subfolder `sub1`, will be possible to get your subfolders with:

```php
$imap->getFolders('INBOX.sub1')
```

**Comment by sergey144010** [comment]
Now I have works just
`$imap->selectFolder('INBOX/Sent');`
This really works.
May be you should not do it issue?

**Comment by sergey144010** [comment]
You mean just change this '/' on this '.'

**Comment by xXXIMMATTHEWXXx** [comment]
I think that works @sergey144010. Not tested but i remember doing something along those lines abit ago

**Comment by natanfelles** [comment]
I did some tests here and I used the the current `getFolders()`.

My results are:

```
[getFolders] => Array
        (
            [0] => Trash
            [1] => Test1
            [2] => Test1.Sub1
            [3] => Test1.Sub1.Sub2
            [4] => Junk
            [5] => Drafts
            [6] => Sent
            [7] => INBOX
        )
```

Thinking about, I believe that the output can be manipulated by the developer. If he know that your server ever has an `INBOX` folder as main folder, he can remove it with `str_replace()` if necessary.

I think a more elegant way would be to get something like this back:

```
[getFolders] => Array
        (
            [Trash] => Array ()
            [Test1] => Array (
                [Sub1] => Array (
                    [Sub2] => Array ()
                )
            )
            [Junk] => Array ()
            [Drafts] => Array ()
            [Sent] => Array ()
            [INBOX] => Array ()
        )
```

But I have not been able to implement yet

**Comment by sergey144010** [comment]
Why get such an array?
That contains  [Trash] => Array () ?
What is the next step?

Sorry, but I don't understand what you want. The first post was on a public class like `getSent`. Now you want this
`[Test1] => Array (
                [Sub1] => Array (
                    [Sub2] => Array ()
                )
            )`
. But then it is inserted here:
`{imap.mail.com/imap/ssl/novalidate-cert}Test1.Sub1.Sub2`
For me `{imap.mail.com/imap/ssl/novalidate-cert}Test1/Sub1/Sub2`
Why convert string->array->string ?
Make two options for return?
1.
`[getFolders] => Array
        (
            [0] => Trash
            [1] => Test1
            [2] => Test1.Sub1
            [3] => Test1.Sub1.Sub2
            [4] => Junk
            [5] => Drafts
            [6] => Sent
            [7] => INBOX
        )`
2.
`[getFolders] => Array
        (
            [Trash] => Array ()
            [Test1] => Array (
                [Sub1] => Array (
                    [Sub2] => Array ()
                )
            )
            [Junk] => Array ()
            [Drafts] => Array ()
            [Sent] => Array ()
            [INBOX] => Array ()
        )`

**Comment by natanfelles** [comment]
Hello.

The idea is not to repeat the folders. Making the structure come out easy to be adapted into in the navigation menu.

**Comment by sergey144010** [comment]
Well, I did it. This is what we talked about?
To install use:
`{
"repositories": [
{
"type": "vcs",
"url": "https://github.com/sergey144010/php-imap-client",
"packagist": false
}
],
"require": {
"SSilence/php-imap-client": "dev-issue_17"
}
}`
Use as:
`
$imap = new ImapClient();
$folders = $imap->getFolders();
var_dump($folders);
`
Want to test it and tell me works properly or not.

**Comment by sergey144010** [comment]
Or may be make pull request?

**Comment by xXXIMMATTHEWXXx** [comment]
If it works it works if it don;t it dont :) That our lives :)
FR if it does not work then someone will make another issue and we can continue from their

**Comment by xXXIMMATTHEWXXx** [comment]
The pull request has been merged. If this is solved with the latest version close it please :)

**Comment by xXXIMMATTHEWXXx** [comment]
I believe that this has been solved. No reply by original author within 12 days. Closing
