### ISSUE TITLE
imap_search method? 

### ISSUE THREAD

**Issue by abdullahseba** [SSilence/php-imap-client#171]
Hi
Is there a method that uses `imap_search` ?
Also is there a way to easily use php IMAP functions that are not included in  php-imap-client with the same login? Saves all those feature requests.

**Comment by xXXIMMATTHEWXXx** [comment]
getImapConnection can get you the imap var. This can be used for those functions. Please, still request features as we are trying to build a  "knowledge base" of code so it works for all devs :)

**Comment by abdullahseba** [comment]
ok will do :)

**Comment by xXXIMMATTHEWXXx** [comment]
Is this solved?

**Comment by abdullahseba** [comment]
yes

**Comment by abdullahseba** [comment]
I tried this but I get `Message: Call to undefined method SSilence\ImapClient\ImapClient::getImapConnection()`
```
$con = $imap->getImapConnection();
      $serch = imap_search($con, 'SUBJECT "test"', SE_UID);

**Comment by xXXIMMATTHEWXXx** [comment]
Did you update?

**Comment by abdullahseba** [comment]
I dont see it here either http://ssilence.github.io/php-imap-client/methods.html

**Comment by xXXIMMATTHEWXXx** [comment]
Those arent up to date

**Comment by abdullahseba** [comment]
oh is it a new feature? Leme try.

**Comment by xXXIMMATTHEWXXx** [comment]
It is per your request ;)

**Comment by abdullahseba** [comment]
Works! thanks.
