### ISSUE TITLE
Class 'SSilence\ImapClient\SubtypeBody' not found in /home1/u8q7m3r8/public_html/require/phpimap/IncomingMessage.php:361

### ISSUE THREAD

**Issue by n00el** [SSilence/php-imap-client#176]
Hi!
Every time I try to open a message, I got this message.
I put every file from the ImapClient to my folder, but it said, SubtypeBody not found. What can I do?

`<b>Fatal error</b>:  Uncaught Error: Class 'SSilence\ImapClient\SubtypeBody' not found in /home1/u8q7m3r8/public_html/require/phpimap/IncomingMessage.php:361
Stack trace:
#0 /home1/u8q7m3r8/public_html/require/phpimap/IncomingMessage.php(178): SSilence\ImapClient\IncomingMessage-&gt;getBody()
#1 /home1/u8q7m3r8/public_html/require/phpimap/IncomingMessage.php(159): SSilence\ImapClient\IncomingMessage-&gt;init()
#2 /home1/u8q7m3r8/public_html/require/phpimap/ImapClient.php(640): SSilence\ImapClient\IncomingMessage-&gt;__construct(Resource id #26, 12, 'decode')
#3 /home1/u8q7m3r8/public_html/cm/inc/foglalasok/foglalas/loadUzenetvaltas.php(33): SSilence\ImapClient\ImapClient-&gt;getMessage(12)
#4 {main}
  thrown in <b>/home1/u8q7m3r8/public_html/require/phpimap/IncomingMessage.php</b> on line <b>361</b><br />`

**Comment by xXXIMMATTHEWXXx** [comment]
Are you able to install via composer we highly recomend this

**Comment by n00el** [comment]
Thanks for your very fast reply! Okey, then i try it!

**Comment by xXXIMMATTHEWXXx** [comment]
Let me know! No problem

**Comment by n00el** [comment]
I try it with composer, but it is still hard for me! :)

But I found a solution: If I require all files at first, (not only that some what I find in this doc: http://ssilence.github.io/php-imap-client/gettingstarted.html) it's working.

`  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/ImapClientException.php";
  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/ImapConnect.php";
  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/ImapClient.php";
  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/Section.php";
  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/Helper.php";
  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/IncomingMessage.php";
  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/IncomingMessageAttachment.php";
  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/TypeAttachments.php";
  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/TypeBody.php";
  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/SubtypeBody.php";
  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/OutgoingMessage.php";
  require_once $_SERVER['DOCUMENT_ROOT']."/require/phpimap/AdapterForOutgoingMessage.php";`

**Comment by xXXIMMATTHEWXXx** [comment]
When using composer are you using the auto loader?

**Comment by n00el** [comment]
Yes!
And sorry for askint it there, but can I search with this library? For e.g. only list emails from a specific email?

**Comment by xXXIMMATTHEWXXx** [comment]
Just got a pc so sorry for not replying. The readme contains a link to the docs :D

**Comment by uomopalese** [comment]
I get a `Fatal error: Uncaught Error: Class 'Imap' not found `, even with the suggested workaround
