### ISSUE TITLE
Mailbox encoding problem

### ISSUE THREAD

**Issue by matiux** [SSilence/php-imap-client#177]
Hi,
i have a problem with getFolders() method.

```
$imapClient = new ImapClient($mailbox, $username, $password, $encryption)
$mailboxes = $imapClient->getFolders('.', 1);
```
I'm connected to my Gmail that contains some mailboxes like `Friends/Giò Rossi`

However, what I see is `Friends/Gi&API- Rossi`

Is there some internal methos which can solve this problem?

Thanks

**Comment by ZoTyA1975** [comment]
You can use this:
mb_convert_encoding($foldername, 'UTF-8', 'UTF7-IMAP')

**Comment by xXXIMMATTHEWXXx** [comment]
Closed because of @ZoTyA1975 solution. Thanks.
