### ISSUE TITLE
Getting the HTML part of an email

### ISSUE THREAD

**Issue by MrRoudeLeiw** [SSilence/php-imap-client#179]
Hello,
Somehow I don't see how I can get the HTML part of this email. I provided an var_dump of the email, and marked the area where the HTML part is positionned with " //////#### WANTED ######"

Thanks for your help.

[mail.txt](https://github.com/SSilence/php-imap-client/files/1136725/mail.txt)

**Comment by diego-vieira** [comment]
https://github.com/SSilence/php-imap-client/issues/157#issuecomment-297911343

```
(string)$mail->message->html
(string)$mail->message->text
```

**Comment by xXXIMMATTHEWXXx** [comment]
Closed. @diego-vieira have the answer
