### ISSUE TITLE
Use secondary interface when making requests to the IMAP

### ISSUE THREAD

**Issue by skynet** [SSilence/php-imap-client#18]
I want to use a secondary interface with a different IP when making requests to the IMAP server. How do I accomplish that?

With curl is as easy as setting up a flag: 
```
curl_setopt($curlh, CURLOPT_INTERFACE, "xxx.xxx.xxx.xxx");
```
For imap the only remaining option is to bind php to a different interface, which is also a pain ...

**Comment by fulldecent** [comment]
I do not see this option in the underlying PHP IMAP functions. Please report this issue upstream to PHP.

**Comment by skynet** [comment]
:+1: Thanks for answering.
