### ISSUE TITLE
Empty mail body as result of run imap_base64 twice

### ISSUE THREAD

**Issue by weba1h** [SSilence/php-imap-client#182]
Subject, test mail in attachment

[original_msg.txt](https://github.com/SSilence/php-imap-client/files/1150285/original_msg.txt)

**Comment by sergey144010** [comment]
You can turn off the decoding, and then decode separately what you need.
```php
getMessage($id, $decode = IncomingMessage::DECODE)
```

**Comment by xXXIMMATTHEWXXx** [comment]
Closed for @sergey144010 's answer
