### ISSUE TITLE
How can I get only the message body

### ISSUE THREAD

**Issue by ZoTyA1975** [SSilence/php-imap-client#183]
Hello,

I'd like to get only the body from a message (the _body part). How can I do that?

`SSilence\ImapClient\SubtypeBody Object
(
    [charset] => iso-8859-2
    [_structure:SSilence\ImapClient\Section:private] => stdClass Object
        (
            [type] => 0
            [encoding] => 1
            [ifsubtype] => 1
            [subtype] => PLAIN
            [ifdescription] => 0
            [ifid] => 0
            [lines] => 18
            [bytes] => 306
            [ifdisposition] => 0
            [ifdparameters] => 0
            [ifparameters] => 1
            [parameters] => Array
                (
                    [0] => stdClass Object
                        (
                            [attribute] => CHARSET
                            [value] => ISO-8859-2
                        )

                    [1] => stdClass Object
                        (
                            [attribute] => FORMAT
                            [value] => flowed
                        )

                )

        )

    [_body:SSilence\ImapClient\Section:private] => xy wrote:

blabla
)`

**Comment by anielka** [comment]
$mail->message->html

**Comment by sergey144010** [comment]
or $mail->message->plain

**Comment by xXXIMMATTHEWXXx** [comment]
Closed as solved.

**Comment by geri777** [comment]
$mail->message->plain ... results in an error: Undefined property: stdClass::$plain

**Comment by geri777** [comment]
DISCOVERY #1:
$mail->message->plain is wrong, it's $mail->message->text

**Comment by geri777** [comment]
DISCOVERY 2:
$mail->message->html->__get('body')
... will give you the html body of the email.
