### ISSUE TITLE
 Trying to get property of non-object IncomingMessage.php, line 364

### ISSUE THREAD

**Issue by a-zubrzycki** [SSilence/php-imap-client#187]
Hey there, 
It's my first post at Github at all. 

I have this issue when in my mailbox are emails from mailer deamons of type - email couldn't be delivered etc. When I delete this feedback message everythings starts to work again. 

Do u need something more? 

![screen01](https://user-images.githubusercontent.com/5747204/29376800-0fc90984-82ba-11e7-858e-8407de117a8f.png)

**Comment by xXXIMMATTHEWXXx** [comment]
Hey! Welcome to the almighty GitHub. Ill be sure to look at this when I get
home. I can currently coming back from vaction. Ill let you know

**Comment by adri-smith** [comment]
Thank you!

**Comment by foxdirect** [comment]
Underneath the FOREACH, I inserted this on new line 363 and it fixed it:
	        if (empty($this->getSection($section, array('class' => $subType)))) continue;

**Comment by xXXIMMATTHEWXXx** [comment]
@sergey144010 wrote that. @sergey144010 ping if you would

**Comment by iBooster** [comment]
I do have the same Error when just simply use this code:

`$emails = $imap->getMessages();`

so this is a bug and will be fixed? (first post on github, since ever :D )

**Comment by xXXIMMATTHEWXXx** [comment]
This may be due yo no messages being their at all

**Comment by iBooster** [comment]
There are about 2600 emails in the inbox folder, so I think that's not the problem

**Comment by xXXIMMATTHEWXXx** [comment]
Hmm I will look into this again

**Comment by iBooster** [comment]
To Help you a little bit, thats the code which I use
`$mailbox = 'von-gerle.de';
	$username = 'myUsername';
	$password = 'myPassword';
	$encryption = Imap::ENCRYPT_SSL; // TLS OR NULL accepted

	$imap = new Imap($mailbox, $username, $password, $encryption);

	$folders = $imap->getFolders();
	$output = '';
	foreach($folders as $folder) {
	    echo $folder;
	}

	// Select the folder INBOX
	$imap->selectFolder('INBOX');
	$overallMessages = $imap->countMessages();
	$unreadMessages = $imap->countUnreadMessages();
	$emails = $imap->getMessages();`

Of course I set the right Username and Password =)

**Comment by xXXIMMATTHEWXXx** [comment]
Hey do you mind updating an re running your code to make sure the lines
march up again

**Comment by iBooster** [comment]
okay, i've updated it, but still the same error.

**Comment by xXXIMMATTHEWXXx** [comment]
it still echos from line 364 correct?

**Comment by iBooster** [comment]
maybe this can help you a bit:
![grafik](https://user-images.githubusercontent.com/32245818/30819667-ba14e564-a21f-11e7-8a88-c27bf70a3293.png)

**Comment by xXXIMMATTHEWXXx** [comment]
The message is cannot access empty ???

**Comment by iBooster** [comment]
sorry, yes the messages is "cannot access empty property"

**Comment by xXXIMMATTHEWXXx** [comment]
Try and remove the \

**Comment by xXXIMMATTHEWXXx** [comment]
Ah! I got it! Remvoe the $ fro, subtype on that line! Let me know

**Comment by iBooster** [comment]
i did, now i get this 'Call to a member function __get() on null'
In Line 377

**Comment by iBooster** [comment]
okay, after i removed the $ in both lines (366, 377) i got the "cannot access empty property" but this time for line 699

![grafik](https://user-images.githubusercontent.com/32245818/30833281-9600bd36-a24e-11e7-9674-923bb848a225.png)

**Comment by xXXIMMATTHEWXXx** [comment]
I will download the code tommrow after school and fully fix this

**Comment by xXXIMMATTHEWXXx** [comment]
Please, update your code with my leastest commits

**Comment by iBooster** [comment]
I am sorry that I have to ask, but how do I update with your commit ? I use composer

**Comment by xXXIMMATTHEWXXx** [comment]
No problem :) I don't remember the command by heart myself lol. Try
composer update. If not just Google it lol

**Comment by xXXIMMATTHEWXXx** [comment]
Did that fix the issue?

**Comment by xXXIMMATTHEWXXx** [comment]
Herooooooooo????????

**Comment by spatnynick** [comment]
Hi the warning on line 699 is still occurring (and some others warnings); in attachment is output from:
var_dump($typeMessage);echo("\n\n"); var_dump($this->message); die;
in coding IncomingMessage.php & ln 699; there is no $this->message->typeMessage->structure existing

[errout.log](https://github.com/SSilence/php-imap-client/files/1359042/errout.log)

**Comment by xXXIMMATTHEWXXx** [comment]
I will look into this later.

**Comment by xXXIMMATTHEWXXx** [comment]
May I see the full stack trace and error? Screenshots are okay

**Comment by spatnynick** [comment]
there is what I get:
PHP Warning:  Creating default object from empty value in
/home/aaa/utils/rf-vypisy/php-imap-client/ImapClient/IncomingMessage.php on
line 385
PHP Notice:  Undefined property: stdClass::$typeMessage in
/home/aaa/utils/rf-vypisy/php-imap-client/ImapClient/IncomingMessage.php on
line 699
PHP Notice:  Trying to get property of non-object in
/home/aaa/utils/rf-vypisy/php-imap-client/ImapClient/IncomingMessage.php on
line 699
PHP Notice:  Trying to get property of non-object in
/home/aaa/utils/rf-vypisy/php-imap-client/ImapClient/IncomingMessage.php on
line 699
PHP Notice:  Undefined property: stdClass::$typeMessage in
/home/aaa/utils/rf-vypisy/php-imap-client/ImapClient/IncomingMessage.php on
line 699
PHP Notice:  Trying to get property of non-object in
/home/aaa/utils/rf-vypisy/php-imap-client/ImapClient/IncomingMessage.php on
line 699
PHP Notice:  Trying to get property of non-object in
/home/aaa/utils/rf-vypisy/php-imap-client/ImapClient/IncomingMessage.php on
line 699


2017-10-07 16:53 GMT+02:00 Matthew Parks <notifications@github.com>:

**Comment by wp-entwickler-at** [comment]
hey there!
I got the same problem and the solution is quiet easy:

![grafik](https://user-images.githubusercontent.com/6277633/33346069-b17b8754-d48e-11e7-8470-9195848854d9.png)

Some Mails don't have a plaintext mailbody.
So you would try to give $objNew a NULL property!
That is the problem, my code is a possible solution.
Greetz and keep up the good work!

**Comment by GregJohnStewart** [comment]
I am having a separate but very similar issue on line 708 of that file:

Notice: Trying to get property of non-object in ... /ImapClient/IncomingMessage.php line 708

I am just trying to set it up, so I am unsure if it is a real bug or I have not setup my connection correctly yet...

**Comment by xXXIMMATTHEWXXx** [comment]
Hey, can you share your connection code?

**Comment by GregJohnStewart** [comment]
Using the advanced constructor;

` new ImapClient([ `
`     'flags' => [ `
`         'service' => ImapConnect::SERVICE_IMAP, `
`         'encrypt' => ImapConnect::ENCRYPT_SSL, `
`         'validateCertificates' => ImapConnect::NOVALIDATE_CERT, `
`     ], `
`    'mailbox' => [ `
`        'remote_system_name' => "<host>.com", `
`    ], `
`    'connect'=>[ `
`        'username'=>"<username>", `
`        'password'=>"<password>" `
`    ] `
` ]) `

**Comment by xXXIMMATTHEWXXx** [comment]
It may be trying to use an ssl connection and ignoring certification

**Comment by mosbror** [comment]
`$obj->__get('structure')` on line 364 returns an empty object for me.
I've added `if(is_object($obj->__get('structure'))) { continue ;}`above line 366

Soved it for me.
![image](https://user-images.githubusercontent.com/10770171/51981739-443b2f80-2494-11e9-82a5-0bc57bf92ecc.png)

**Comment by cbielich** [comment]
I am having the same issue where after `$emails = $imap->getMessages();` it breaks. But this is only happening to me when I access a office365 account. I tried adding wp-entwickler-at suggestion but that didn't work.
