### ISSUE TITLE
Attachment not working for gmail?

### ISSUE THREAD

**Issue by Ajtak** [SSilence/php-imap-client#19]
Hi. Attachment content not working for gmail?

How to fix it?

Thank you,

**Comment by natanfelles** [comment]
Hello, @Ajtak !
Some solution to this problem with the attachments in Gmail?
Do you know if this works in other mail server?

Thanks. I am starting to work in this project now...

**Comment by natanfelles** [comment]
Hello!
This bus has been fixed here: https://github.com/natanfelles/php-imap-client/commit/de9df0bd3271170f0a8248bf0496fc6d4aee612e

I will do a Pull resquest when I implement the ability to define what dparameters to use automatically.

**Comment by xXXIMMATTHEWXXx** [comment]
@Ajtak If you are still active close this issue please
