### ISSUE TITLE
Warning: array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by oliwin** [SSilence/php-imap-client#190]
Warning: array_merge(): Argument #2 is not an array in C:\xampp\htdocs\tmp\ImapClient\ImapClient.php on line 852

Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\tmp\ImapClient\IncomingMessage.php on line 509

**Comment by xXXIMMATTHEWXXx** [comment]
I have not seen this in the current version.. please use composer to update and make sure you are doing stuff correctly. Tell me if not...

**Comment by xXXIMMATTHEWXXx** [comment]
Closed due to inactivity. If this is still can issues please open it again with more detail
