### ISSUE TITLE
When I'm trying to Get all folders as array of strings its showing error

### ISSUE THREAD

**Issue by deepak458** [SSilence/php-imap-client#201]
I'm Using Code as you Say Like
`$folders = $imap->getFolders();
foreach($folders as $folder) {
    echo $folder;
}`

**But It's Showing Error Like**

Notice: Array to string conversion in C:\xampp\htdocs\ats\mail-2\mail-4\inbox.php on line 26
Array

**Comment by cleitongarcia** [comment]
```
        $folders = $imap->getFolders();

        foreach($folders as $key => $value) {
            echo $key . '</br>';
        }
```

**Comment by cleitongarcia** [comment]
**This not is a issue!**

**Comment by xXXIMMATTHEWXXx** [comment]
Yep. Just invalid PHP syntax.
