### ISSUE TITLE
showing error when try to connect wit another email id

### ISSUE THREAD

**Issue by deepak458** [SSilence/php-imap-client#202]
Hello Dear,
My All Code working good but when i'm trying to change my email address its not work. everything is right its connection and also getting folders but not emails. you can see my attachment for code
[mail-action.txt](https://github.com/SSilence/php-imap-client/files/1638550/mail-action.txt)
 and its showing error like that.

**Please Help Me OUT.**

    `INBOX
     Notice: Trying to get property of non-object in 
     C:\xampp\htdocs\ats\classes\phpmail\ImapClient\IncomingMessage.php on line 364

     Fatal error: Uncaught Error: Cannot access empty property in 
     C:\xampp\htdocs\ats\classes\phpmail\ImapClient\IncomingMessage.php:366 Stack trace: #0 
     C:\xampp\htdocs\ats\classes\phpmail\ImapClient\IncomingMessage.php(178): 
     SSilence\ImapClient\IncomingMessage->getBody() #1 
     C:\xampp\htdocs\ats\classes\phpmail\ImapClient\IncomingMessage.php(159): 
     SSilence\ImapClient\IncomingMessage->init() #2 
     C:\xampp\htdocs\ats\classes\phpmail\ImapClient\ImapClient.php(644): 
     SSilence\ImapClient\IncomingMessage->__construct(Resource id #18, 164, 'decode') #3 
     C:\xampp\htdocs\ats\classes\phpmail\ImapClient\ImapClient.php(567): 
     SSilence\ImapClient\ImapClient->getMessage(164) #4 C:\xampp\htdocs\ats\mail\mail-
     action.php(55): SSilence\ImapClient\ImapClient->getMessages() #5 
     C:\xampp\htdocs\ats\mail\inbox.php(4): include('C:\\xampp\\htdocs...') #6 {main} thrown in 
     C:\xampp\htdocs\ats\classes\phpmail\ImapClient\IncomingMessage.php on line 366

     Notice: Unknown: Invalid quoted-printable sequence: =>. > (errflg=3) in Unknown on line 0`

**Comment by xXXIMMATTHEWXXx** [comment]
Please use a new instance for the imap client for EACH email, if you implement a multi mail system, please use a new object for each email and its login.

**Comment by deepak458** [comment]
Ok thank you
