### ISSUE TITLE
Where to put pull-requests?

### ISSUE THREAD

**Issue by likemusic** [SSilence/php-imap-client#207]
### Feature request or bug
Bug

### If a bug, what did you expect to happen?
'dev'-branch in git repository or actualized info in [Contributing page](http://ssilence.github.io/php-imap-client/contributing.html)

### If a bug, what happened?
There is no 'dev' brunch in git repository. But on [Contributing page](http://ssilence.github.io/php-imap-client/contributing.html) said 

> We do _not_ accept pull request to the "master" branch.
> ... Your feature much be put in the "dev" branch ...

**Comment by xXXIMMATTHEWXXx** [comment]
Sorry for this mistake, you are meant to fork and commit then merge. I will fix this.

**Comment by xXXIMMATTHEWXXx** [comment]
I have add a commit. Please check and confirm.

**Comment by likemusic** [comment]
Looks good.
