### ISSUE TITLE
Undefined property: stdClass::$date

### ISSUE THREAD

**Issue by stdex** [SSilence/php-imap-client#21]
Undefined property: stdClass::$date in <b>Imap.php</b> on line <b>207</b><br />

If mail server do not return date or return date like this:
  ["MailDate"]=>
  string(26) " 4-Sep-2015 08:29:02 +0000"
  ["Size"]=>
  string(4) "1768"
  ["udate"]=>
  int(1441355342)

**Comment by xXXIMMATTHEWXXx** [comment]
This is because of out dated mail servers. I would recommend updating your mail sever
