### ISSUE TITLE
Incorrect charset

### ISSUE THREAD

**Issue by stdex** [SSilence/php-imap-client#22]
If mail server return subjects like this:
["subject"]=> string(21) "=?koi8-r?B?+sHLwdo=?="

Your lib use function convertToUtf8 and incorrect encode it.

It's work for me:
    //"=?koi8-r?B?".base64_encode($subject)."?="
    $header = imap_header($imap, $i);
    $subj = str_replace('=?koi8-r?B?','',$header->subject);
    $subj = str_replace('?=','',$subj);
    var_dump(base64_decode($subj));

And it's return me correct subject.

**Comment by artemiusgreat** [comment]
I also faced issue with KOI8-R, this happened with emails from Yandex. 
Here is the method that I used to work around the issue.

/**
     * Identify encoding by charset attribute in header
     * @param $id
     * @return string
     */
    protected function setEncoding($id)
    {
        $header = imap_fetchstructure($this->imap, $id);
        $params = $header->parameters ?: [];

        foreach ($params as $k => $v) {
            if (stristr($v->attribute, 'charset')) {
                return $v->value;
            }
        }

        return 'utf-8';
    }

Then, override existing method with encoding with this one : 

/**
     * Apply encoding defined in header
     * @param $str
     * @return string
     */
    function convertToUtf8($str) {
        return mb_convert_encoding($str, 'utf-8', $this->encoding);
    }

**Comment by xXXIMMATTHEWXXx** [comment]
@stdex @artemiusgreat  Thanks. If you can @artemiusgreat add this in a pr. If not ill gladly do it :)

**Comment by xXXIMMATTHEWXXx** [comment]
Fixed. Please close this @stdex
