### ISSUE TITLE
getMessage($id) returns wrong message

### ISSUE THREAD

**Issue by geri777** [SSilence/php-imap-client#220]
When I pull the last 20 messages and then want to access a specific message I get the wrong one.
The message I get is not within the 20 messages of $allEmails. 
I am using POP3 not IMAP.

    $allEmails = $imap->getMessages(20);
    $cntr = 1;
    foreach($allEmails As &$email) {
         // add the ID to each email
         $email['id] = $cntr;
         $cntr++;
    }
    var_dump($allEmails);

    //get the Message No. 3 
    var_dump($imap->getMessage(3));

**Comment by xXXIMMATTHEWXXx** [comment]
Arrays start at 0 not 1. If you want to access #3 you need to request #4

**Comment by geri777** [comment]
I thought it is 1-based, because when I look in function checkMessageId($id) I find ...
    if($id > $this->countMessages()){
         throw new ImapClientException('Bad message number');
    }

But anyway - THIS IS NOT THE PROBLEM unfortunately. I get a very old message (maybe number 500 or so), which is not part of the $imap->getMessages(20).

**Comment by xXXIMMATTHEWXXx** [comment]
Lets take for example an array with 49 messages. Count messages would
return 50. But if you ask for the number 50, the exception is thrown. Get
it?

On the part about the message, just grab that section

>

**Comment by geri777** [comment]
If you have 50 messages, count will return 50, wouldn't it? If you have a Null-based  index the highest id can be 49. In this case the checkMessageId would be if($id >= $this->countMessages()) 
(note the equal sign). 
Please post the part with "grab that section" again. If I click it it's empty. Many thanks!

**Comment by geri777** [comment]
I now understand what's going wrong. It is getMessages which makes the troubles. We get all messages from the mailbox using `imap_search($this->imap, 'ALL');` These messages should have an ID (counter). But instead we do several operations on the message array (like array_reverse and array_chunk) and get completely new message numbers then. These message numbers do not correlate with the message numbers of the imap stream any more.
