### ISSUE TITLE
saveAttachments problem

### ISSUE THREAD

**Issue by tolgacinar** [SSilence/php-imap-client#238]
Save attachments with this function but cant open files. Files are breaking

**Comment by YaWK** [comment]
I've had the same issue. You need to base64_decode the attachment body. I've changed the line of file_put_contents[...] in ImapClient\SaveAttachments method to this:

**This solved the problem for me:**
_file_put_contents($dir.DIRECTORY_SEPARATOR.$newFileName, base64_decode($attachment->body);_

**Comment by ggiacomoo** [comment]
thanks, why not pulled?!?!

**Comment by tuptuptup** [comment]
@YaWK @ggiacomoo It's good solution, but not for each attachment. Some of attachment need quoted_printable_decode.

$att=base64_decode($attachment->body);
if(strlen($att)<10){
	file_put_contents($dir.DIRECTORY_SEPARATOR.$newFileName, quoted_printable_decode($attachment->body));
}else{
	file_put_contents($dir.DIRECTORY_SEPARATOR.$newFileName, $att);
}

**Comment by tolgacinar** [comment]
Solved.

[https://github.com/SSilence/php-imap-client/issues/238#issuecomment-530195536](https://github.com/SSilence/php-imap-client/issues/238#issuecomment-530195536)
