### ISSUE TITLE
Is it possible to make private methods protected to add ability for inheritance?

### ISSUE THREAD

**Issue by artemiusgreat** [SSilence/php-imap-client#27]
Initial class is great but it misses some important functions, e.g. search messages by criteria. 

Let's say, I or any other developer would like to create child class derived from base one and add such method but I need to get access to open IMAP connection. 

Thus, at least $imap property should be protected instead of private.

**Comment by xXXIMMATTHEWXXx** [comment]
@artemiusgreat  Thanks! Will edit in a future pr :)

**Comment by xXXIMMATTHEWXXx** [comment]
@artemiusgreat  ha! Didn't see this was already fixed. Close this if you don't mind :)

**Comment by natanfelles** [comment]
Now is possible search by criteria. Look at: #54 and http://php.net/manual/en/function.imap-search.php if do you want.
