### ISSUE TITLE
getting a bug in Imap.php

### ISSUE THREAD

**Issue by Vikram-dev** [SSilence/php-imap-client#3]
I have download the fresh version of this IMap package.
There is a bug in line no 183 in IMap.php. there is a parse error the functional array used in true condition is giving error. While same code using in toAddress() is showing correct.
Please suggest me how should i remove this.

**Comment by fulldecent** [comment]
This is now fixed in the latest version. Recommending close.

**Comment by xXXIMMATTHEWXXx** [comment]
@Vikram-dev  if you are still active please close this issue

**Comment by natanfelles** [comment]
Close.
