### ISSUE TITLE
Question : Close Imap connection?

### ISSUE THREAD

**Issue by t-me** [SSilence/php-imap-client#32]
How can i close a imap connection?

I see the 

```
    /**
     * close connection
     */
    function __destruct() {
        if($this->imap!==false)
            imap_close($this->imap);
    }
```

but how do i call it?
i have looked at [http://php.net/manual/en/language.oop5.decon.php](url) but i did not see the answer there.

Have i overlooked a function?

**Comment by SSilence** [comment]
You can close the connection by unsetting the variable holding the Imap Object (unset $imap).

But I have added a function for explicitly closing the connection.
