### ISSUE TITLE
Error while trying to delete

### ISSUE THREAD

**Issue by kurdtpage** [SSilence/php-imap-client#38]
Here is my code:

```
<?php
    if(!class_exists('Imap')) require "Imap.php";
    $imap = new Imap($mailbox, $username, $password, $encryption);
    if($imap->isConnected() === false) die($imap->getError());
    $imap->selectFolder("INBOX");
    $emails = $imap->getMessages();
    if(count($emails)>0){ //if theres a new email
        echo "There are ".count($emails)." emails found<br>\n";
        foreach($emails as $email) { //for every new email
            echo "Processing UID: ".$email['uid']."<br>\n"; //$email['uid'] is 4
            //do some stuff, import attachments, etc
            $read = $imap->setUnseenMessage($email['uid']); //mark as read
            if($imap->deleteMessage($email['uid'])) echo "deleted<br>\n"; //delete the email
            else echo " error deleting email<br>\n";
        }
    }
?>
```

I get the following errors:

> ( ! ) Notice: Unknown: Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.000 + 0.000 secs). (errflg=2) in Unknown on line 0
> 
> ( ! ) Notice: Unknown: IMAP protocol error: Error in IMAP command UID COPY: Invalid uidset (0.000 + 0.000 secs). (errflg=2) in Unknown on line 0
> 
> ( ! ) Notice: Unknown: Error in IMAP command UID COPY: Invalid uidset (0.000 + 0.000 secs). (errflg=2) in Unknown on line 0

**Comment by nekromoff** [comment]
Happens to me as well, definitely a bug

**Comment by nekromoff** [comment]
Moreover, no messages get deleted, all stay unchanged in INBOX

**Comment by nekromoff** [comment]
Notice: Unknown: Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (errflg=2) in Unknown on line 0

Notice: Unknown: Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (errflg=2) in Unknown on line 0

Notice: Unknown: Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (errflg=2) in Unknown on line 0

Notice: Unknown: Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (errflg=2) in Unknown on line 0

Notice: Unknown: Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (errflg=2) in Unknown on line 0

Notice: Unknown: Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (errflg=2) in Unknown on line 0

Notice: Unknown: Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (errflg=2) in Unknown on line 0

**Comment by nekromoff** [comment]
fix - edit Imap.php and replace deleteMessages function with this:
`
    /**
     * delete messages
     *
     * @return bool success or not
     * @param $ids array of ids
     */
    public function deleteMessages($ids) {
        foreach ($ids as $id) {
            imap_delete($this->imap, $id, FT_UID);
        }
        /*
        if( imap_mail_move($this->imap, implode(",", $ids), $this->getTrash(), CP_UID) == false)
            return false;
        */
        return imap_expunge($this->imap);
    }`

**Comment by kurdtpage** [comment]
If this is merged into the normal file, I can close the issue.

**Comment by xXXIMMATTHEWXXx** [comment]
@kurdtpage I will add this in with a pr later thanks!
