### ISSUE TITLE
Cant get e-mail address in "FROM', has name only.

### ISSUE THREAD

**Issue by Antonyous** [SSilence/php-imap-client#40]
["from"]=> string(59) "Antonyous" ["date"]=> string(31) "Sun, 18 Sep 2016 21:51:07 +0300"

**Comment by SonnyLCD** [comment]
I have same problem, did you find a solution ?

**Comment by xXXIMMATTHEWXXx** [comment]
Hello, I am reopening this issues, can you explain what you are trying to do what what happend?

**Comment by SonnyLCD** [comment]
When fetching/reading 1 email. 

Using method: 

`getMessage() `

and subsequently 

`formatMessage() `

only returns the name and not email of the sender.

I tried adding various tests to the email array like this:

```
'structure' => imap_fetchstructure($this->imap, $id),
'overview' => imap_fetch_overview ($this->imap, $id),
'header'    => imap_fetchheader($this->imap, $id),
```

But neither holds the email of the sender.

Let me know if I need to provide you with more info.

Many thanks!

**Comment by xXXIMMATTHEWXXx** [comment]
try this:
edit
https://github.com/SSilence/php-imap-client/blob/master/ImapClient/ImapClient.php#L536
so that it looks like
`'from'      => $header->from[0],`
and tell me the output

**Comment by SonnyLCD** [comment]
My bad! ... it returns the string like: 

`John Smith <john.smith@domain.com>`

Is just a matter of splitting it. Would be nice if having a method to get each separately, but is not a big problem really.

**Comment by xXXIMMATTHEWXXx** [comment]
Just what i was thinking. THANKS for reporting this. Will be fixed. For now ill keep it open
