### ISSUE TITLE
Script doesn't support inline attachments

### ISSUE THREAD

**Issue by artemiusgreat** [SSilence/php-imap-client#41]
Script doesn't support **inline** attachments.
Specifically, some files, maybe just big files, sent from **mail.ru**
To fix this replace all such places

> ...->dparameters[0]->value; // in methods getAttachment and getAttachments

with this 

> empty($partStruct->dparameters) ? $partStruct->parameters[0]->value : $partStruct->dparameters[0]->value;

and replace this check 

> if (strtolower($part->disposition) == "attachment")

with this

> if (strtolower($part->disposition) == "attachment" || strtolower($part->disposition) == "inline")

Sorry, don't have time to make patch for this.

**Comment by xXXIMMATTHEWXXx** [comment]
@artemiusgreat I will see if this is still an issue and if it is ill make a pr. Thanks

**Comment by natanfelles** [comment]
#54

**Comment by xXXIMMATTHEWXXx** [comment]
@artemiusgreat  as @natanfelles has fixed this issue in his latest pr. If you are still active on github please close this issue.
