### ISSUE TITLE
How can I create an eml file from a mail

### ISSUE THREAD

**Issue by nickbe** [SSilence/php-imap-client#42]
Is there a method for creating eml files?

**Comment by xXXIMMATTHEWXXx** [comment]
Not currently. Note that this repo is for connecting to a server and manageing emails. Note for sending them. SO, If you want to use email files you can hack something together yourself with https://github.com/PHPMailer/PHPMailer

**Comment by xXXIMMATTHEWXXx** [comment]
Fixed with #71

**Comment by xXXIMMATTHEWXXx** [comment]
Closing as the fix has been merged!
