### ISSUE TITLE
Mac Mail, inline embedded images and attachments

### ISSUE THREAD

**Issue by SonnyLCD** [SSilence/php-imap-client#51]
Hi all

Thanks for a very nice imap client!

However, I have a problem that I haven't been able to solve.

When writing an email in Apple Mail (that sends attachments inline), that contains both inline images and an attachment, like an PDF or Excel file, then it breaks. The $mail['body_embed'] does no longer return the whole email. Typically it breaks on the first embedded image, and cuts mail there. Attachments are available, but now the embedded image is also listed as an attachment, rather than render in email. And I haven't been able to get the content in another way.

Also, having issues with getting filenenames of files attached inline in Mac Mail.

I tried, directly, with the PHP IMAP extension, but haven't found anything useful, yet anyway.

Hope anyone has an idea.

Greetings
/sonny

**Comment by xXXIMMATTHEWXXx** [comment]
@SonnyLCD  Hmm... do you mind showing your code? I may be able to hack my way around and fix this later

**Comment by SonnyLCD** [comment]
Sure

I using the imap class in a Phalcon PHP MVC setup. Is pretty straightforward, I add the imap class to the application in the Dependency Injector, and Implement it in a Controller.

I get the mail like this:

`$mail = $imap->getMessage($message_id, $withbody = true);`

I render the mail content simply like this for now:

`$mail['body_embed']` 

It works great when only having images that are embedded in the email. 

But it breaks, when mail is mixed with inline images and attachments , sent from Mac Mail, that sends everything inline. Mail sent from Gmail or others that attach files works just fine, the $mail['body_embed'] renders the whole email, with images and I can get attachments, -only thing is that the inline images also show up as attachments, but they can be filtered out.

I tried using various methods to get the whole mail using the PHP/IMAP extension (http://php.net/manual/en/book.imap.php) which SSilence imap also builds on. But didnt really find a way to solve it, yet...

Hope this explains it well enough ?

**Comment by xXXIMMATTHEWXXx** [comment]
Yes. Thank you. I will try and hack something up later. Thank you for
reporting this issue :)

**Comment by fr0z3nfyr** [comment]
For me, in the latest version as of date, `$email['body_embedd']` wasn't being set at all. Upon investigation, found that `$this->embed` was not being set to true at all. So to fix it, I just added
`$this->embed = true;    // alternatively, $this->embed = $this->setEmbed(true);` in `getAttachments(...) {...}` like this:
```
protected function getAttachments($imap, $mailNum, $part, $partNum) {
    ...
    if (isset($part->parts)) {
        ...
    } else if (isset($part->disposition)) {
	if (in_array(strtolower($part->disposition), array('attachment', 'inline'))) {
		$partStruct = imap_bodystruct($imap, $mailNum, $partNum);
		$reference = isset($partStruct->id) ? $partStruct->id : "";
		if (strtolower($part->disposition) == 'inline') {
			$this->inline = true;
			$this->embed = true;    // added this
		}
        ...
    } ...
    return $attachments;
}
```
You may want to look into the latest code to fix this. Cheers!!

**Comment by SonnyLCD** [comment]
Great! many thanks to **fr0z3nfyr** .. this solved the problem.
