### ISSUE TITLE
Reformat Code Style

### ISSUE THREAD

**Issue by natanfelles** [SSilence/php-imap-client#55]
Hello!

What do you think about to reformat this source using tha [PSR-1/PSR-2](http://www.php-fig.org/psr/psr-2/) Code Style. This is native in some IDEs and the code is more pretty. Also suggest updating the PHP Doc, I also have done something locally.

Waiting reponse for PR #54 to upload.

**Comment by xXXIMMATTHEWXXx** [comment]
I like it. I would go ahead
