### ISSUE TITLE
method getAttachments not working for outlook.com

### ISSUE THREAD

**Issue by vinod8081** [SSilence/php-imap-client#6]
HI,
I am using the imap library its working great. But for outlook.com not giving the attachments.
I thing the need to modify the method getAttachments. I have tried but its not giving the attachments.

**Comment by dezeyer** [comment]
i use zoho mail. when i get a mail by id, var_dump, i can see my attachment, but getAttachment($mailid) is given false. i halse had to remove the $header line in getAttachment, it causes errors and is not used in that function

**Comment by dezeyer** [comment]
And so i added this function to the class...

/**
     * return content of messages attachment
     *
     * @return file name
     * @param $email_number id of the message
     * @param $DOCROOT where the docroot is
     */
    public function saveAttachment($email_number,$DOCROOT) {
        /* get information specific to this email */
        $structure = imap_fetchstructure($this->imap,$email_number);

        $attachments = array();
        if(isset($structure->parts) && count($structure->parts)) {
            for($i = 0; $i < count($structure->parts); $i++) {
                $attachments[$i] = array(
                    'is_attachment' => false,
                    'filename' => '',
                    'name' => '',
                    'attachment' => '');

                if($structure->parts[$i]->ifdparameters) {
                    foreach($structure->parts[$i]->dparameters as $object) {
                        if(strtolower($object->attribute) == 'filename') {
                            $attachments[$i]['is_attachment'] = true;
                            $attachments[$i]['filename'] = $object->value;
                        }
                    }
                }

                if($structure->parts[$i]->ifparameters) {
                    foreach($structure->parts[$i]->parameters as $object) {
                        if(strtolower($object->attribute) == 'name') {
                            $attachments[$i]['is_attachment'] = true;
                            $attachments[$i]['name'] = $object->value;
                        }
                    }
                }

                if($attachments[$i]['is_attachment']) {
                    $attachments[$i]['attachment'] = imap_fetchbody($this->imap, $email_number, $i+1);
                    if($structure->parts[$i]->encoding == 3) { // 3 = BASE64
                        $attachments[$i]['attachment'] = base64_decode($attachments[$i]['attachment']);
                    }
                    elseif($structure->parts[$i]->encoding == 4) { // 4 = QUOTED-PRINTABLE
                        $attachments[$i]['attachment'] = quoted_printable_decode($attachments[$i]['attachment']);
                    }
                }             
            } // for($i = 0; $i < count($structure->parts); $i++)
        } // if(isset($structure->parts) && count($structure->parts))
            
        if(count($attachments)!=0){
            foreach($attachments as $at){
                if($at['is_attachment']==1){
                    $at['filename'] = date("Y-m-d_H-i-s", time())."_".$at['filename'];
                    if(stripos($at['filename'], ".tiff") !== false || stripos($at['filename'], ".tif") !== false){
                        $path = "/documents/tiff/";
                        $ext = "tiff";
                    }elseif(stripos($at['filename'], ".pdf") !== false){
                        $path = "/documents/pdf/";
                        $ext = "pdf";
                    }else{
                        $path = "/documents/";
                    }
                    file_put_contents($DOCROOT.$path.$at['filename'], $at['attachment'],FILE_APPEND );
                    if(isset($ext)){
                        return array("path" => $DOCROOT.$path.$at['filename'], "ext" => $ext);
                    }else{
                        return false;
                    }
                }
            }
        }else{
            return false;
        }
    }

**Comment by natanfelles** [comment]
Hello!
This bus has been fixed here: https://github.com/natanfelles/php-imap-client/commit/de9df0bd3271170f0a8248bf0496fc6d4aee612e (comment the Gmail and uncomment Outlook lines)

I will do a Pull resquest when I implement the ability to define what dparameters to use automatically.

**Comment by xXXIMMATTHEWXXx** [comment]
@vinod8081 i dont know if you are still an active github user, but if you are please close this issue
