### ISSUE TITLE
Where is ID ?

### ISSUE THREAD

**Issue by Blount** [SSilence/php-imap-client#60]
Hello.

I need to use ImapClient to manipulate mail via imap.

When I call getUnreadMessages, array returned does not contains any ID key. Also, can't get the attachments.
I added (line 236) : 
'id'       => $id,
Before : 
'uid'       => $uid,

This work fine.
But, is it correct ?

**Comment by xXXIMMATTHEWXXx** [comment]
The attachments should be working. Can you add some more info on that? I will ad get id in the future if it has not. I do not know though. Are you using the very newest version as it has been updated

**Comment by Blount** [comment]
Arf, I used an old version. I think downloaded the last version, sorry.

Also, my attachment is not detected, because the content disposition not define in my mail message.

Extract of mail source :
---
Content-Type: Application/XXXXXX;name=XXXXXX.doc
Content-Transfer-Encoding: base64
Content-Description: CP/ACC

CONFIDENTIALCONTENT

-----

CONFIDENTIALCONTENT is the encoded content of attachment.
Content-Disposition is missing.

**Comment by kurdtpage** [comment]
Is this the same as issue #26 ?

**Comment by Blount** [comment]
No. This issue is solve by downloading master version of ImapClient.
To solve my attachment detection, I defined a default disposition (line 927) : 
```php
        protected function getAttachments($mailNum, $part, $partNum) {
        $attachments = array();

        if (!isset($part->parts)
            && !isset($part->disposition)
            && (!isset($part->subtype) || !in_array($part->subtype, array('JPEG', 'GIF', 'PNG')))
        ) {
            $part->disposition = 'attachment';
        }

        if (isset($part->parts)) {
```

After this patch, my attachment is correctly return by "getAttachments".

**Comment by Blount** [comment]
I publish my patch here : 
https://github.com/Blount/php-imap-client/commit/52300f192c4cb9e27074a0e83d39c70fe3c72109

**Comment by sergey144010** [comment]
I think you need to make pull request.

**Comment by xXXIMMATTHEWXXx** [comment]
Yes. If you make a patch or fix please make a pull request.

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks. If this is fixed please close the issue!
