### ISSUE TITLE
getFolders return empty array

### ISSUE THREAD

**Issue by Blount** [SSilence/php-imap-client#63]
When I call getFolders to retrieve all folders in Mailbox, an empty array is returned.
Sent, Trash, Junk, etc, are missing.
I see that $this->mailbox contains INBOX : 
`{address:993/imap/notls/ssl/novalidate-cert/user="XXX"}INBOX`
This because you call getResponseMailbox at line 150 : 
https://github.com/SSilence/php-imap-client/blob/master/ImapClient/ImapClient.php#L150
When I replace this line by : 
```php
$this->mailbox = $connect->getMailbox();
```
This work fine.

Also, why call getResponseMailbox ?

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks for pointing that out. Will be fixed. Glad your using this library and helping to improve it :)

**Comment by sergey144010** [comment]
Well fix it. In the connectDefault () and connectAdvanced ().

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks. Looks good!

**Comment by xXXIMMATTHEWXXx** [comment]
Merged. If it is not fixed comment again and explain any thing else relating to this issue :)

**Comment by Blount** [comment]
It's work for me.
Thx.
