### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [SSilence/php-imap-client#65]
Hello! Thanks everyone who has been contributing to this library!
I think that for the the errors we can throw ("Could not connect" and so on) should have an explanation
So in either the README or the wiki or even a new markdown file we should let the developers know what each error means and how to fix them.

**Comment by kurdtpage** [comment]
Good idea!

**Comment by sergey144010** [comment]
Maybe you mean to fix the more detailed answer, for example
`throw new ImapClientException('Error connecting to '.$mailbox);`
fix on
``throw new ImapClientException('Error connecting to '.$mailbox. '. Check your connection settings and Internet connection.');``

**Comment by xXXIMMATTHEWXXx** [comment]
Sorry. What i mean is not in the code. Another file in the repo for developers to use and read. Thats just what i think but that way works too. We can just see what everyone likes the most

**Comment by sergey144010** [comment]
I think need create docs/guide folders. Inside README.md with content like 'Install, Usage, Connect settings, Error' which will be links to the appropriate files. And accordingly create files Install.md, Usage.md and other. And in the future you can then create the appropriate folders with translations in various languages, like  docs/guide-fr,  docs/guide-de and other.

**Comment by xXXIMMATTHEWXXx** [comment]
^^ sounds good to me

**Comment by sergey144010** [comment]
https://github.com/composer/composer/blob/master/doc/01-basic-usage.md

> Package Names
> 
> The package name consists of a vendor name and the project's name. Often these will be identical - the vendor name just exists to prevent naming clashes. It allows two different people to create a library named json, which would then just be named igorw/json and seldaek/json.
> 
> Here we are requiring monolog/monolog, so the vendor name is the same as the project's name. For projects with a unique name this is recommended. It also allows adding more related projects under the same namespace later on. If you are maintaining a library, this would make it really easy to split it up into smaller decoupled parts.

**Comment by sergey144010** [comment]
Your pull request file composer.json

**Comment by sergey144010** [comment]
And may be add docs/guide folders. And Inside ... redme and etc. Because next step -> docs/guide-fr, docs/guide-de and other.

**Comment by xXXIMMATTHEWXXx** [comment]
Fixed as of pr #68 Closing
