### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [SSilence/php-imap-client#67]
Hello! I thought it would be a good idea to make periodic releases once a stable version is released. What does everyone think of this?

**Comment by sergey144010** [comment]
In case of need.

**Comment by xXXIMMATTHEWXXx** [comment]
Just so development files don't get in the way

**Comment by kurdtpage** [comment]
There have been a lot of changes made recently, thanks everybody. Once a stable version is reached, should the major version number change? Say to version 2.0 or something? I think there have been enough changes made from the original code to warrant this. Thoughts?

**Comment by xXXIMMATTHEWXXx** [comment]
I like that ^^^

**Comment by xXXIMMATTHEWXXx** [comment]
Just noticed that this would also help with composer

**Comment by hhdivil** [comment]
Yes definitely do this!  Create a dev branch we can fork from that instead

**Comment by xXXIMMATTHEWXXx** [comment]
This has been fixed with our work towards project 2.0!

**Comment by koenhoeijmakers** [comment]
Would be nice to have an actual release so we can use versioning in composer `"ssilence/php-imap-client":"^1.0"`, relying on the `dev-master` is really bad as you can never be certain that things aren't broken in between commits.
