### ISSUE TITLE
examples wrong id

### ISSUE THREAD

**Issue by rickoneeleven** [SSilence/php-imap-client#7]
in your examples you have $emails[0]['id'] but it's actually uid

thanks and great script by the way
r

**Comment by tomjoad2000** [comment]
+1. At least with microsoft imap.

**Comment by tomjoad2000** [comment]
Something's wrong.. At row 190:
        // fetch unique uid
        $uid = imap_uid($this->imap, $id);

So what's $id? Running office365 imap returns no id-value at all on getMessages().

**Comment by tomjoad2000** [comment]
FYI: Couldn't get this library working with IMAP towards office365, but had no problems with other library (https://github.com/barbushin/php-imap)

**Comment by xXXIMMATTHEWXXx** [comment]
@rickoneeleven  if you are still active on github please close this issue

**Comment by rickoneeleven** [comment]
Closed
