### ISSUE TITLE
Can't install with composer

### ISSUE THREAD

**Issue by Hirbod** [SSilence/php-imap-client#74]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package ssilence/php-imap-client could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details
```

Also tried to add "minimum-stability: dev", but it won't work. Giving up!

**Comment by xXXIMMATTHEWXXx** [comment]
Hmmm! Never give up! I will investigate this!

**Comment by xXXIMMATTHEWXXx** [comment]
Our package name did go lowercase, so i edited them in the files. Download all current files and try again

**Comment by Hirbod** [comment]
I used this composer entry to install:
https://github.com/SSilence/php-imap-client/blob/master/docs/guide-en/Install.md

**Comment by Hirbod** [comment]
It's not about usage problems, I just can't install with composer. Not sure if changing the namespace is the root for this problem.

**Comment by xXXIMMATTHEWXXx** [comment]
It seems composer has trouble reading the library and knowing that it exist. I would register it so its a simple  `composer require` but i am waiting on @SSilence. For now ill look further into it and may rewrite composer.json. Thank you for _both_ of your issues!

**Comment by Hirbod** [comment]
you're welcome!

**Comment by xXXIMMATTHEWXXx** [comment]
I cant seem to find a way around this with out some re writing for composer to fully work. I currently dont have some, @sergey144010  @natanfelles  can you guys look into this?

**Comment by xXXIMMATTHEWXXx** [comment]
I believe that this has been fixed, untill the first version (Big o' 2.0) release is out, use this command to install with composer: `composer require ssilence/php-imap-client dev-master`

**Comment by xXXIMMATTHEWXXx** [comment]
Noted as not fixed. If anyone else can get this working please try as I cannot

**Comment by sergey144010** [comment]
Already fixed ?

**Comment by xXXIMMATTHEWXXx** [comment]
It should be now. Someone fixed our namespace's so we just need someone to install via composer and init the script.

**Comment by xXXIMMATTHEWXXx** [comment]
Marked as closed. This should be fixed, If it is not comment back
