### ISSUE TITLE
Error in documentation / link broken

### ISSUE THREAD

**Issue by Hirbod** [SSilence/php-imap-client#75]
The link to the "current list of methods" is broken.
Link to: https://github.com/SSilence/php-imap-client/blob/master/docs/guide-en/docs/guide-en/Methods.md

<img width="532" alt="bildschirmfoto 2017-01-02 um 21 10 11" src="https://cloud.githubusercontent.com/assets/504909/21595599/ee38255c-d12f-11e6-880d-9e10834873dc.png">

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks! Will fix right now!

**Comment by xXXIMMATTHEWXXx** [comment]
Fixed. Auto closed for some reason. Weird. But thank you again for reporting this!

**Comment by Hirbod** [comment]
As soon as you send a PR with a #number, it will auto-close :)

**Comment by xXXIMMATTHEWXXx** [comment]
Ooo fancy fancy !
