### ISSUE TITLE
Feature Request: Example script for extracting image attachements

### ISSUE THREAD

**Issue by bonelifer** [SSilence/php-imap-client#82]
### If a feature request, what do you want to be added or changed?
An example script that checks if the Subject CONTAINS the "SuperSecretCODE" and then extracts GIF, JPG or PNG attachements to a folder and marks the mail as seen.

**Comment by xXXIMMATTHEWXXx** [comment]
I like that. Will be added soon

**Comment by sergey144010** [comment]
Check your note with the new source code.
Try this
$imap->saveAttachmetsMessagesBySubject('Special text', 'path/to/save/attach', 'charset for special text');

**Comment by xXXIMMATTHEWXXx** [comment]
Speaking of that. I was wondering if you would add attachment extraction to
the examples

**Comment by xXXIMMATTHEWXXx** [comment]
This issue has been fixed with our latest code. It is now possible and docs are being updated. Thank you for helping our library!
