### ISSUE TITLE
About getMessagesByCriteria()

### ISSUE THREAD

**Issue by SonnyLCD** [SSilence/php-imap-client#84]
Hi again

Earlier I was using getMessages() to get mail list, and the afterwards to fix pagination with the whole list. But after getMessagesByCriteria() was added I tried this, but had 2 issues.

I found solutions for both that works for us, so wanted to share it, just in case others have same problems.

**Mailbox order:**
First of all the imap script got the oldest mails first, also pagination did reverse. It may just be my silly mail server. But I fixed it by doing array_reverse, changing from this:

```
public function getMessagesByCriteria(...)
	{
		$emails = array();
		$result = imap_search($this->imap, $criteria);
```

to this:

```
public function getMessagesByCriteria(...)
	{
		$emails = array();
		$result = array_reverse(imap_search($this->imap, $criteria));
```

Maybe it is not a general issue, but fixed the problem with our mail server.

**Pagination:**
trying to paginate through the mailboxes also gave problems. Passing parameters like this to function:

`$imap->getMessagesByCriteria($criteria = '', $number = 0, $start = 10, $order = 'DESC', $withbody = FALSE, $embed_images = FALSE);`

If `$start = 0` then all works well, but if for instance `$start = 10` then function returns an empty resultset.

A fix was changing this (deleting first line):

```
$ids = array_chunk($ids, $number);
$ids = array_slice($ids[0], $start, $number);
```

to this:

`$ids = array_slice($ids, $start, $number);`

And at least with our mail server it worked.

Thanks a lot for a nice imap library! .. I'm sure that we soon will have a great, well tested and very solid imap solution with this...

**Comment by xXXIMMATTHEWXXx** [comment]
@sergey144010  @natanfelles  @SSilence. I have done the same on my end. Can one of you guys test it as well so it comes from 3 sources? Please?

**Comment by xXXIMMATTHEWXXx** [comment]
It appears no one else is going to confirm. Make a pr or i will later :)
