### ISSUE TITLE
No validate Cert

### ISSUE THREAD

**Issue by candidoalbertosilva** [SSilence/php-imap-client#87]
Add to code 

$enc = '/imap/novalidate-cert';

**Comment by xXXIMMATTHEWXXx** [comment]
I can't understand what your trying to ask here. Read the docs or open a new issue with the proper format

**Comment by candidoalbertosilva** [comment]
public function __construct($mailbox, $username, $password, $encryption = false) {
        $enc = '';
        if($encryption!=null && isset($encryption) && $encryption=='ssl')
            $enc = '/imap/ssl';
        else if($encryption!=null && isset($encryption) && $encryption=='tls')
            $enc = '/imap/tls';
        **if($encryption=='novalidate-cert'){
              $enc = '/imap/novalidate-cert';
        }**
        $this->mailbox = "{" . $mailbox . $enc . "}";
        $this->imap = @imap_open($this->mailbox, $username, $password);
    }

**Comment by xXXIMMATTHEWXXx** [comment]
Check the most recent code. ImapClient no longer makes the connection. This is done by another class

**Comment by xXXIMMATTHEWXXx** [comment]
https://github.com/SSilence/php-imap-client/blob/master/docs/guide-en/Usage.md#advanced-connecting will show you how to add no validate cert.
