### ISSUE TITLE
Sent from macOS Mail, Inline attachment breaks email

### ISSUE THREAD

**Issue by SonnyLCD** [SSilence/php-imap-client#88]
Hi

We noticed that if a user drops in an attachment inside an email (at least on Apple Mail), -like in between the text, then when opening it in (php-imap-client) webmail the mail is truncated just at the attachment, none of the content, text and so after this point is there.

The issue is probably in the `get_part()` function, here:

```
// multipart
if ($structure->type == 1) {
	foreach ($structure->parts as $index => $subStruct) {
		$prefix = "";
		if ($partNumber) {
			$prefix = $partNumber . ".";
		}
		$data = $this->get_part($imap, $uid, $mimetype, $subStruct, $prefix . ($index + 1));
		if ($data) {
			return $data;
		}
	}
}
```

If I change to below, the whole email is there, but now the HTML formatting is lost:

```
// multipart
if ($structure->type == 1) {
	foreach ($structure->parts as $index => $subStruct) {
		$data = $this->get_part($imap, $uid, $mimetype, $subStruct, $partNumber);
		if ($data) {
			return $data;
		}
	}
}
```

The attachments is there so no problem with that. Is only that either mail is truncated, or HTML formatting is lost, -for all emails, also without attachments.

**Comment by xXXIMMATTHEWXXx** [comment]
Sounds weird to me. Will look into it

**Comment by SonnyLCD** [comment]
updated to latest version, and a lot of bugs are gone. I made some small fixes, I dont know if they are specific to our mail server, but will post them tomorrow.

Seems that this issue, that mail is truncated after an inline attachment now only is a problem when mail is sent from Apple Mail... Anyway, I will test and get back on this tororrow

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks! If you dont want to type it here feel free to make a pull request

**Comment by SonnyLCD** [comment]
I will send it later with description. I made some small changes too, maybe specific to our mail server, but I will describe them...
As far as I can see this library only has a few smaller issues left to fix...

Great job!

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks!

**Comment by SonnyLCD** [comment]
Thanks, the latest update is a big step forward.

However I still have issues with emails sent from macOs Mail, that makes a bit of a mess with attachments and other things.

The problem is still if you in a macOS mail place an attachment within the text, then the mail truncates the rest of the email when rendering the email with this library. The mail renders text until the inline attachment, but cuts there.

No problem with getting the attachments though, they are all listed perfectly. 

It is only email text that is truncated, and seems that only when sent from macOS Mail.




**Smaller changes:**
I made some changes to the script to fix some small issues to make it work with our mail server. 
Ofcourse I can not be sure if these things are general, but in case som others can use it:

**`function getMessagesByCriteria()`:**

Line 427:

`$result = imap_search($this->imap, $criteria);`

Was changed to this, to show newest messages first:

`$result = array_reverse(imap_search($this->imap, $criteria));`

Lines 439 and 440:

```
$ids = array_chunk($ids, $number);
$ids = array_slice($ids[0], $start, $number);
```

Was changed to this, to make pagination work:

`$ids = array_slice($ids, $start, $number);`

**`function getMessage()`:**

Line: 508

`return $this->formatMessage($id, $withbody, $embed_images);`

Was changed to this, to pass on `$uid` instead of `$msg_number`, to open the correct mail:

```
$msg_number = imap_msgno($this->imap,$id);
return $this->formatMessage($msg_number, $withbody, $embed_images);
```

**`function formatMessage()`:**

Line: 541

`'from'      => $header->from[0],`

Was changed to this, to get sender info:

`'from'      => $header->fromaddress,`

**Comment by xXXIMMATTHEWXXx** [comment]
I do believe i changed to code. Make sure i updated it all correctly

**Comment by SonnyLCD** [comment]
I am using latest version ... is easy to reproduce actually. When writing an email in macOS Mail, then when writing an email, drop in a file, PDF, Excel or whatever in the mail, and write text again below.

Then when rendering mail in webmail using the library it cuts right where attachment was dropped in.

**Comment by xXXIMMATTHEWXXx** [comment]
With the code you provided, does it work?

**Comment by SonnyLCD** [comment]
no, I haven't been able to solve this problem. I know that macOS Mail handles Attachments in a non-standard way, like Content-Disposition.

As long as it is only images then no problem, they will render nicely.

But if you send another file like a Excel file, PDF or something that does not render, then mail is simply cut and does not render after the first attachment...

**Comment by xXXIMMATTHEWXXx** [comment]
We need to look further into Mac os mail. Do you have a contact?

**Comment by SonnyLCD** [comment]
a contact ?

**Comment by xXXIMMATTHEWXXx** [comment]
Someone who develops for them or would know into?

**Comment by SonnyLCD** [comment]
no, no insider contacts I'm afraid. But I googled the topic a lot, there is a lot of writing about it. So it is a wellknown issue. Is something about how to traverse the mail structure. I have some code to finish, but I will look into it sometime tomorrow and post what I find here in the thread...

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks. Let me know I'll do some digging aswell

**Comment by SonnyLCD** [comment]
It seems that it is something with the encoding of the attachment that makes either: `formatMessage()` or `attachments2name()` break, when trying to render an non-image attachment inline.

For displaying the email we mainly have:

1. header
2. Mail body
3. Attachments

Problem is only rendering of the mail body. The attachments are all available in the attachments array.

So solution is to ignore all non-image attachments when rendering the email ? these will be available in the attachment array.

**Here below screendumps of what happens.**
To the left viewed in a regular mail client, to the right, mail rendered with this imap library, where one can see that mail simply stops rendering at the first attachment. This does NOT happen if mail only contains images, they will render nicely, it is only if having non-image attachments.

![imap_error](https://cloud.githubusercontent.com/assets/6242703/22965393/a9fe3f8e-f35d-11e6-97eb-5a14a010a00d.gif)

**Comment by xXXIMMATTHEWXXx** [comment]
I have found some more info on this issue. It seems that mac mail tends to send attachments in the content disposition.

**Comment by SonnyLCD** [comment]
yes exactly, I have the impression that somewhere down the road, when looping through the mail structure of an email with these attachments in an email from Mac Mail, the rendering gets derailed, and just stops. I was thinking to look into where this happens, and if we somehow can get the imap library to ignore it and carry on rendering the email, then it would be alright. We can extract the attachments for download without problems...

**Comment by xXXIMMATTHEWXXx** [comment]
Yeah. Only hard part for us is finding out when the loop stops or fails. I will continue to look into this

**Comment by SonnyLCD** [comment]
yep, agree. I will look too...

**Comment by sergey144010** [comment]
Check your note with the new source code.

**Comment by xXXIMMATTHEWXXx** [comment]
This issue should be fixed with our latest updates. For now, this is marked as inactive.

**Comment by xXXIMMATTHEWXXx** [comment]
Marked as inactive 5 days ago and there is still no reply. This issues has been fixed with our latest updates. Closing...
