### ISSUE TITLE
Maybe a little bug in getAttachments() function

### ISSUE THREAD

**Issue by SonnyLCD** [SSilence/php-imap-client#93]
### Feature request or bug
Bug. 

Probably linked to the issue with mails sent from Apple Mail, with attachments sent as content disposition.

### If a bug, what happened?
IMAP library threw an error and stopped rendering inbox.

Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /home/prod/falckbox-web-platform/app/vendor/imap/Imap.php on line 1096

The problem was in this function:  `getAttachments() ` in the `if (isset($part->disposition))` part:

This line create the problem and where error was thrown (`$part->parameters` if it is not an array):

`} else if ($part->parameters[0]) {`

So I changed from this:

```
if (isset($part->dparameters[0])) {
	$parameters = $part->dparameters[0];
} else if ($part->parameters[0]) {
	$parameters = $part->parameters[0];
}
```

to this, and it worked:

```
if (isset($part->dparameters[0])) {
	$parameters = $part->dparameters[0];
} elseif ( is_array($part->parameters) && isset($part->parameters[0]) 	) {
	$parameters = $part->parameters[0];
} elseif ( is_object($parameters = $part->parameters) ) {
	$parameters = $part->parameters;
}
```

Seems that, again, this crazy nesting of objects and arrays in the mail structure caused created another headache...

### If a bug, did you do these steps?
Yes using latest version

**Comment by SonnyLCD** [comment]
oops, was too fast. It didn't just solve the problem, it also meant that library stopped rendering images in the mail..

**Comment by sergey144010** [comment]
Check your note with the new source code.

**Comment by xXXIMMATTHEWXXx** [comment]
Please, check your code without latest updates. If you do not respond soon, this issue will be marked as solved.

**Comment by xXXIMMATTHEWXXx** [comment]
Marked as inactive.

**Comment by xXXIMMATTHEWXXx** [comment]
OPInactive. We assume this issue has been fixed as I have merged the pull request and this appears to be fixed. Closing...
