### ISSUE TITLE
ErrorException in ImapClient.php line 428: array_reverse() expects parameter 1 to be array, boolean given

### ISSUE THREAD

**Issue by megaket4up** [SSilence/php-imap-client#94]
When there are no letters in the box, imap_search($this->imap, $criteria) returns false.

ErrorException in ImapClient.php line 428: 
array_reverse() expects parameter 1 to be array, boolean given

**Comment by xXXIMMATTHEWXXx** [comment]
Thank you for reporting this! By letter do you mean emails?

**Comment by megaket4up** [comment]
yes

**Comment by xXXIMMATTHEWXXx** [comment]
Okay thank you! This just seems to be a simple null pointer check. Will be fixed soon. If you want you can can make a pull request or I will fix it up later
