### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by andykkkk** [SSilence/php-imap-client#97]
How can I save attachments ?

**Comment by xXXIMMATTHEWXXx** [comment]
This feature is currently a w.i.p if you would like to speed up this
process make a pull request

**Comment by andykkkk** [comment]
ok. i`l see what I can do

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks we hope to get this working soon!

**Comment by andykkkk** [comment]
so, i tried this code:
`public function downloadAttachment($uid, $partNum, $encoding) {
		
		$partStruct = imap_bodystruct($this->imap, imap_msgno($this->imap, $uid), $partNum);
		
		$filename = $partStruct->dparameters[0]->value;
		$message = imap_fetchbody($this->imap, $uid, $partNum, FT_UID);
		
		switch ($encoding) {
			case 0:
			case 1:
				$message = imap_8bit($message);
				break;
			case 2:
				$message = imap_binary($message);
				break;
			case 3:
				$message = imap_base64($message);
				break;
			case 4:
				$message = quoted_printable_decode($message);
				break;
		}
		
		header("Content-Description: File Transfer");
		header("Content-Type: application/octet-stream");
		header("Content-Disposition: attachment; filename=" . $filename);
		header("Content-Transfer-Encoding: binary");
		header("Expires: 0");
		header("Cache-Control: must-revalidate");
		header("Pragma: public");
		echo $message;
	}`
I take it from https://www.sitepoint.com/exploring-phps-imap-library-2/

for me it`s worked

**Comment by xXXIMMATTHEWXXx** [comment]
With one attachment correct?

**Comment by andykkkk** [comment]
yes.

**Comment by xXXIMMATTHEWXXx** [comment]
Our problem is with 2 or more attachments

**Comment by andykkkk** [comment]
ok. i`ll see what i can do

**Comment by xXXIMMATTHEWXXx** [comment]
Thank you

**Comment by sergey144010** [comment]
Check your note with the new source code.

**Comment by xXXIMMATTHEWXXx** [comment]
Please, Check your code with, our latest updates. If you do not respond in the next few days this issue will be marked as solved and closed.

**Comment by xXXIMMATTHEWXXx** [comment]
Issues closed due to inactivity. Solved a good bit ago.
