### ISSUE TITLE
Feature Request: message_id

### ISSUE THREAD

**Issue by TrueShutDown** [SSilence/php-imap-client#98]
I think it is a good idea to add message_id to the array that is returned from the getMessage() function and more specifically to formatMessage().
This field identifies message between sessions and is important. #

**Comment by xXXIMMATTHEWXXx** [comment]
Sounds great. I'll be sure to add this

**Comment by sergey144010** [comment]
Check your note with the new source code.

**Comment by xXXIMMATTHEWXXx** [comment]
This feature was added by @sergey144010. Closing this issue!
